# -*- coding: utf-8 -*-
"""Contenu français du site de Spyke Technologies Inc.

Modifiez le texte ici, puis exécutez « python3 build.py » pour régénérer les pages.
Aucun tarif, taux, plafond de capacité, nom de client ni condition contractuelle
ne doit figurer dans ce fichier.
"""

C = {
    # ------------------------------------------------------------------ chrome
    "lang": "fr",
    "lang_name": "Français",
    "other_lang": "en",
    "other_lang_label": "EN",
    "other_lang_aria": "Switch to English",
    "skip": "Passer au contenu principal",
    "dir_prefix": "../",
    "nav": [
        ("offers.html", "Offres"),
        ("pathway.html", "Parcours"),
        ("industries.html", "Secteurs"),
        ("about.html", "À propos"),
    ],
    "nav_cta": ("contact.html", "Démarrer une conversation"),
    "nav_open": "Ouvrir le menu de navigation",
    "nav_close": "Fermer le menu de navigation",
    "theme_to_dark": "Passer au mode sombre",
    "theme_to_light": "Passer au mode clair",
    "home_label": "Spyke Technologies Inc. — accueil",
    "breadcrumb_home": "Accueil",
    "footer_tagline": "Définition d’applications minières, plateformes de démonstration, productisation et mise à l’échelle.",
    "footer_nav_title": "Site",
    "footer_offers_title": "Offres",
    "footer_contact_title": "Contact",
    "footer_legal": "© {year} Spyke Technologies Inc. Tous droits réservés.",
    "footer_location": "Région de Montréal, Québec, Canada",
    "footer_note": "Services-conseils indépendants fondés sur l’expérience professionnelle générale, l’analyse indépendante et l’information accessible au public.",
    "li_personal_label": "Sandy Pyke sur LinkedIn",
    "li_company_label": "Spyke Technologies sur LinkedIn",
    "fig": "Fig.",

    "offers_meta": [
        {
            "slug": "offer-a-mining-application-framing-sprint.html",
            "tag": "Offre A",
            "name": "Sprint de cadrage d’application minière",
            "short": "Définir le bon problème minier avant de construire.",
            "stage": "Définir le problème minier",
            "question": "Où cette technologie peut-elle créer une valeur pratique en contexte minier, et que doit prouver un premier démonstrateur?",
            "start": "Technologie ou concept crédible; aucune application minière ni contexte de démonstration suffisamment défini.",
            "outcome": "Cas d’usage minier retenu et contexte de démonstration, parcours des parties prenantes, plan de preuve et feuille de route de validation sur 90 jours.",
            "duration": "1 à 2 semaines d’effort, normalement en 2 à 3 semaines calendrier.",
            "img": "application-framing.webp",
            "alt": "Mine à ciel ouvert à l’heure bleue, avec des routes de halage descendant dans la fosse",
        },
        {
            "slug": "offer-b-mining-demonstration-platform-definition.html",
            "tag": "Offre B",
            "name": "Définition de plateforme de démonstration minière",
            "short": "Spécifier le démonstrateur terrain qu’un client minier peut réellement évaluer.",
            "stage": "Construire la preuve",
            "question": "Quel démonstrateur faut-il construire, quel flux de travail minier doit-il soutenir et quelles preuves doit-il produire?",
            "start": "Technologie éprouvée ou prototype précoce; application et contexte de démonstration approuvés.",
            "outcome": "Spécification d’une plateforme de démonstration déployable sur le terrain, définition modulaire et des interfaces, plan de validation, matrice de traçabilité, registre de risques et dossier de décision exécutif.",
            "duration": "Normalement 5 à 7 semaines calendrier après l’approbation du contexte; A + B combinées, normalement 7 à 10 semaines calendrier.",
            "img": "field-demonstrator.webp",
            "alt": "Boîtier d'instrumentation robustifié monté sur le toit de la salle des machines d'une pelle minière à ciel ouvert, en retrait du garde-corps et hors de l'enveloppe de travail",
        },
        {
            "slug": "offer-c-mine-ready-productization-assessment.html",
            "tag": "Offre C",
            "name": "Évaluation de productisation prête pour la mine",
            "short": "Rendre visible l’écart entre un démonstrateur et un produit commercial.",
            "stage": "Productiser pour la mine",
            "question": "Que faut-il changer avant que le démonstrateur puisse être validé, fabriqué, installé, entretenu, soutenu et mis à l’échelle?",
            "start": "Application définie et démonstrateur ou prototype représentatif, fonctionnel ou validé sur le terrain.",
            "outcome": "Base de productisation fondée sur les preuves, grille d’évaluation, registre d’écarts priorisé, vue de transition démonstrateur-produit, feuille de route indicative de 18 à 24 mois et modèle d’exécution recommandé.",
            "duration": "Jusqu’à 4 semaines calendrier, en mode principalement à distance.",
            "img": "productization-bench.webp",
            "alt": "Banc d’électronique avec instrumentation et boîtier industriel partiellement assemblé",
        },
        {
            "slug": "offer-d-prototype-to-channel-readiness-program.html",
            "tag": "Offre D",
            "name": "Programme de préparation du prototype au réseau de distribution",
            "short": "Transformer une feuille de route approuvée en exécution gouvernée et en capacité interne.",
            "stage": "Déployer à grande échelle avec confiance",
            "question": "Comment convertir la feuille de route en programme exécutable et bâtir la capacité de livraison requise pour la mise à l’échelle?",
            "start": "Base de productisation approuvée ou preuves équivalentes, commanditaire exécutif, financement et responsable de produit désigné.",
            "outcome": "Plan d’exécution gouverné, leadership technique à fort levier, coordination technique des partenaires, progression par jalons de préparation et transfert de capacité.",
            "duration": "Surge : normalement 2 à 6 mois; Exécution : normalement 6 à 18 mois; Maintien : en continu.",
            "img": "channel-readiness.webp",
            "alt": "Rangée de boîtiers d’équipement robustifiés identiques sur un banc d’assemblage",
        },
    ],

    "stages": [
        ("Définir le problème minier", "Offre A", "Est-ce la bonne application minière et le bon contexte de démonstration à poursuivre?"),
        ("Construire la preuve", "Offre B", "Quel démonstrateur déployable faut-il construire et quelles preuves doit-il produire?"),
        ("Productiser pour la mine", "Offre C", "Que faut-il changer avant que le démonstrateur devienne un produit commercial reproductible?"),
        ("Déployer à grande échelle avec confiance", "Offre D", "Comment exécuter le travail et bâtir la capacité de livraison requise pour la mise à l’échelle?"),
    ],

    # ------------------------------------------------------------------- home
    "home": {
        "file": "index.html",
        "title": "Spyke Technologies Inc. — Application minière, démonstration et productisation",
        "desc": "Spyke Technologies aide les équipes technologiques qualifiées à définir la bonne application minière, à spécifier des démonstrateurs déployables sur le terrain, à évaluer la préparation à la productisation et à diriger le travail requis pour la mise à l’échelle.",
        "hero_eyebrow": "Conseil en technologies minières",
        "hero_h1_a": "De l’application minière au démonstrateur terrain, jusqu’au ",
        "hero_h1_accent": "produit prêt pour la mine et le réseau.",
        "hero_sub": "Spyke Technologies Inc. aide les équipes technologiques qualifiées à définir la bonne application minière avant de construire, à spécifier des démonstrateurs déployables sur le terrain, à évaluer la préparation à la productisation et à diriger les travaux de robustification, de validation, de préparation à la fabrication, de déploiement et de service requis pour la mise à l’échelle.",
        "hero_cta1": "Trouver votre point d’entrée",
        "hero_cta2": "Voir les quatre offres",
        "hero_alt": "Galerie de mine souterraine éclairée par les phares d’un équipement",
        "stats": [
            ("Expérience", "30+ ans", "R-D, déploiement et soutien en technologies minières"),
            ("Structure", "4 offres progressives", "Chacune avec son point d’entrée et sa décision de sortie"),
            ("Modèle", "Un leader technique senior", "Plus la capacité de livraison que votre étape exige"),
            ("Basé à", "Montréal, QC", "Au service d’équipes canadiennes et internationales"),
        ],
        "pos_label": "Positionnement",
        "pos_h2": "Un prototype fonctionnel n’est pas le sommet. C’est le camp de base.",
        "pos_p1": "De nombreuses technologies sont prometteuses en laboratoire, en projet pilote ou dans un secteur voisin. L’adoption minière exige davantage : la technologie doit résoudre un problème opérationnel réel, s’intégrer au flux de travail de la mine, être démontrée de façon crédible sur le terrain, puis mûrir en un produit capable de survivre, d’être validé, fabriqué, installé, entretenu, soutenu et mis à l’échelle.",
        "pos_p2": "Les équipes de technologies minières se heurtent à ce que nous appelons la « montagne des approbations ». Chaque exigence client, contrainte de site, observation terrain, besoin de certification, limite de fabrication, exigence de service ou attente de distributeur révèle un nouveau jalon de préparation. La façon la plus rapide de construire le mauvais produit minier est de partir de la technologie plutôt que du problème minier, du contexte d’exploitation et de la preuve requise.",
        "pos_note": "La « montagne des approbations » est un cadre de communication, et non une prétention de contrôle sur les approbations de tiers.",
        "stages_label": "Le parcours",
        "stages_h2": "Définir le problème minier. Construire la preuve. Productiser pour la mine. Déployer avec confiance.",
        "stages_intro": "Quatre étapes, quatre offres. Chacune part d’une base de preuves distincte, répond à une question différente et produit une prochaine décision définie. Elles sont complémentaires — et non des versions allégées d’un même mandat.",
        "stages_decision": "Décision permise",
        "offers_label": "Offres",
        "offers_h2": "Commencez à l’étape qui correspond à vos preuves.",
        "offers_intro": "Vous ne commencez pas à un niveau de service prédéterminé. Vous commencez là où se trouvent réellement vos preuves, votre maturité produit et votre prochaine décision.",
        "offers_more": "Lire l’offre complète",
        "route_label": "Points d’entrée",
        "route_h2": "Vous ne savez pas où vous situer?",
        "route_intro": "L’aiguillage par maturité est délibéré. Le tableau ci-dessous associe l’incertitude que vous portez aujourd’hui à l’offre conçue pour la résoudre.",
        "route_head": ("Votre situation actuelle", "Incertitude principale", "Offre"),
        "route_cta": "Voir le parcours complet et les règles de progression",
        "readiness_label": "Domaines de préparation",
        "readiness_h2": "La préparation minière s’évalue sur sept domaines.",
        "readiness_intro": "Un démonstrateur peut prouver une capacité technique précieuse et demeurer loin d’un déploiement reproductible. Voici les domaines examinés dans une Évaluation de productisation prête pour la mine.",
        "readiness": [
            "Architecture produit et système",
            "Environnement minier et robustification",
            "Préparation embarquée, applicative, infonuagique, données et communications",
            "Parcours de vérification, validation, certification et conformité",
            "Fabricabilité, testabilité et préparation de la chaîne d’approvisionnement",
            "Déploiement, service et soutien sur le cycle de vie",
            "Préparation du réseau de distribution et de l’exécution",
        ],
        "delivery_label": "Modèle de livraison",
        "delivery_h2": "Un leader technique. La bonne capacité de livraison.",
        "delivery_p1": "Spyke Technologies fournit un leadership produit senior en technologies minières là où il crée le plus de valeur : traduction opérationnelle minière, définition des exigences et des interfaces, stratégie de productisation, intégration technique, direction des jalons de préparation, réduction des risques, coordination des partenaires et transfert de capacité.",
        "delivery_p2": "Le travail d’implantation détaillé est réalisé par votre équipe ou par des spécialistes qualifiés lorsque approprié. La contractualisation directe par le client avec les firmes d’ingénierie, laboratoires, fabricants, installateurs, prestataires de service et partenaires de distribution est la norme — afin que le mandat ne devienne pas le chemin critique et que votre organisation en ressorte plus capable plutôt que plus dépendante.",
        "delivery_alt": "Ingénieurs examinant des plans techniques lors d’une revue de conception",
        "bound_label": "Cadre de travail",
        "bound_h2": "Des responsabilités claires.",
        "bound_p1": "Vous conservez la propriété du produit, les décisions commerciales, les relations clients, les dépenses, les relations directes avec les fournisseurs et partenaires lorsque possible, l’autorité finale de mise en production et les responsabilités de fabricant officiel.",
        "bound_p2": "Spyke Technologies n’est pas une firme de stratégie généraliste, une agence de placement, un fabricant à contrat, un intégrateur de systèmes officiel, un laboratoire ou organisme de certification, un service de représentation commerciale, ni un substitut à vos responsabilités de fabricant officiel. Aucun mandat ne garantit l’accès à un site minier, l’approbation d’un client, le parrainage d’un projet pilote, une certification, l’adéquation au marché ou un succès commercial.",
        "bound_p3": "Spyke Technologies offre des services-conseils indépendants fondés sur l’expérience professionnelle générale, l’analyse indépendante et l’information accessible au public. Aucun renseignement confidentiel, exclusif ou constituant un secret commercial appartenant à un employeur, client, fournisseur ou partenaire actuel ou ancien n’est utilisé, divulgué ou rendu accessible.",
        "cta_h2": "Commencez avec les preuves que vous avez.",
        "cta_p": "Une courte conversation confidentielle suffit habituellement à déterminer votre étape et la prochaine décision à prendre.",
        "cta_btn": "Démarrer une conversation",
    },

    # ----------------------------------------------------------------- offers
    "offers": {
        "file": "offers.html",
        "title": "Offres — Spyke Technologies Inc.",
        "desc": "Quatre offres progressives : Sprint de cadrage d’application minière, Définition de plateforme de démonstration minière, Évaluation de productisation prête pour la mine et Programme de préparation du prototype au réseau de distribution.",
        "eyebrow": "Offres",
        "h1": "Quatre offres. Un seul parcours de maturité.",
        "lead": "Chaque offre part d’une base de preuves distincte, répond à une question client différente, comporte une frontière délibérée et produit une prochaine décision définie. L’achèvement d’une offre n’oblige aucune des parties à passer à la suivante.",
        "table_label": "Vue d’ensemble",
        "table_head": ("Offre", "Point de départ", "Question résolue", "Résultat principal", "Durée typique"),
        "cards_label": "Les offres",
        "cards_h2": "Ce que produit chaque mandat.",
        "detail_more": "Détail complet de l’offre",
        "detail_best": "Convient à",
        "detail_out": "Résultat principal",
        "rules_label": "Progression",
        "rules_h2": "Comment les offres s’articulent.",
        "rules": [
            "Une équipe disposant d’une technologie crédible, mais sans application minière définie, commence normalement par l’Offre A.",
            "L’Offre B commence après l’approbation de l’Offre A, ou lorsqu’une documentation équivalente d’application et de contexte, approuvée par le client, existe déjà.",
            "Les Offres A et B peuvent être vendues ensemble comme un seul mandat à jalons, avec une porte formelle d’approbation du contexte entre les deux.",
            "Une équipe disposant d’une application définie et d’un démonstrateur représentatif fonctionnel peut commencer directement à l’Offre C.",
            "Une équipe disposant d’une base de productisation complétée peut être considérée directement pour l’Offre D, sous réserve de validation de l’adéquation et de la portée.",
            "L’Offre D commence normalement par une phase Surge délimitée; le passage à l’Exécution exige une autorisation distincte du client.",
            "La progression repose sur les preuves, la maturité, la préparation, l’autorité décisionnelle et une portée approuvée séparément — jamais sur une vente incitative automatique.",
            "Une offre ne peut jamais se substituer au travail requis à l’étape de maturité suivante.",
        ],
        "cta_h2": "Quelle offre correspond à vos preuves?",
        "cta_p": "Si la réponse n’est pas évidente, la page Parcours expose en détail la logique d’aiguillage, les événements déclencheurs et les critères d’adéquation.",
        "cta_btn": "Démarrer une conversation",
        "cta_btn2": "Voir le parcours",
    },

    # ---------------------------------------------------------------- pathway
    "pathway": {
        "file": "pathway.html",
        "title": "Parcours et points d’entrée — Spyke Technologies Inc.",
        "desc": "Aiguillage par maturité, événements déclencheurs, règles d’entrée et de progression, et critères d’adéquation des mandats de Spyke Technologies.",
        "eyebrow": "Parcours",
        "h1": "Votre point d’entrée dépend des preuves que vous détenez déjà.",
        "lead": "Les équipes de technologies minières arrivent à des points très différents : une hypothèse de marché non validée, un prototype de laboratoire, un démonstrateur ayant fonctionné en essai terrain, ou une feuille de route approuvée en attente d’exécution. Le point d’entrée doit correspondre à l’incertitude, et non à un palier de service.",
        "chain_label": "Chaîne de valeur",
        "chain_h2": "Quatre étapes, quatre décisions.",
        "chain_head": ("Étape", "Offre", "Décision client permise"),
        "route_label": "Aiguillage par maturité",
        "route_h2": "Associez votre situation à un point d’entrée.",
        "route_head": ("Situation du client", "Incertitude principale", "Offre appropriée"),
        "routes": [
            ("Technologie ou concept crédible, mais aucun problème minier précis, flux de travail cible, contexte de démonstration ou objectif de preuve",
             "Où cette technologie doit-elle créer une valeur pratique en contexte minier, et que doit-elle prouver d’abord?",
             "Offre A", "offer-a-mining-application-framing-sprint.html"),
            ("Technologie éprouvée, prototype de laboratoire ou système précoce; contexte approuvé ou candidat crédible; aucune définition du démonstrateur au niveau des exigences",
             "Quel démonstrateur faut-il construire, quel flux de travail doit-il soutenir et quelles preuves doit-il produire?",
             "Offre B", "offer-b-mining-demonstration-platform-definition.html"),
            ("Un démonstrateur ou prototype représentatif existe pour une application minière définie, mais le déploiement reproductible demeure incertain",
             "Que faut-il changer avant que le système puisse être validé, fabriqué, installé, entretenu, soutenu et mis à l’échelle?",
             "Offre C", "offer-c-mine-ready-productization-assessment.html"),
            ("Une feuille de route de productisation ou des preuves équivalentes existent; le parrainage, le financement, l’autorité décisionnelle et la volonté d’exécuter sont en place",
             "Comment convertir la feuille de route en programme exécutable et bâtir la capacité requise pour un déploiement à grande échelle?",
             "Offre D", "offer-d-prototype-to-channel-readiness-program.html"),
        ],
        "trig_label": "Événements déclencheurs",
        "trig_h2": "Signaux indiquant qu’il est temps de commencer.",
        "trig_groups": [
            ("Offre A — étape de l’application", [
                "Une capacité éprouvée dans un autre secteur — détection, IA, automatisation, communications, électrification, technologies environnementales, robotique ou systèmes de données — est envisagée pour le secteur minier.",
                "Un fondateur, un investisseur, un accélérateur, un incubateur, un OEM ou un groupe d’innovation demande où la technologie pourrait créer une valeur pratique en contexte minier.",
                "Plusieurs applications minières plausibles existent, mais l’équipe n’arrive pas à choisir la première avec confiance.",
                "Un premier démonstrateur pertinent pour la mine est sur le point d’être financé et l’équipe veut éviter de concevoir autour d’un cas d’usage présumé.",
                "Un client précoce ou un contact minier a exprimé de l’intérêt, mais la demande est trop large ou contradictoire pour devenir un mandat de développement.",
                "L’équipe maîtrise sa technologie, mais pas les flux de travail miniers, les interfaces d’équipement, les contraintes d’exploitation, les attentes d’entretien, les rôles d’acheteur ou les réalités d’accès aux sites.",
                "Un récit de cas d’usage minier crédible est requis pour une discussion avec un investisseur, une demande de subvention, une conversation avec un partenaire ou une revue interne de type « go/no-go ».",
            ]),
            ("Offre B — étape du démonstrateur", [
                "Une technologie éprouvée doit être démontrée de façon crédible à l’intérieur d’un flux de travail minier.",
                "Un système de laboratoire, un capteur sur trépied, un produit industriel adapté ou une configuration pilote ne constitue pas encore une plateforme de démonstration déployable sur le terrain.",
                "Un site minier potentiel est intéressé, mais une définition de système pratique est requise avant de s’engager dans une construction.",
                "L’application cible et le contexte de démonstration sont approuvés ou déjà suffisamment documentés.",
                "Une définition au niveau des exigences est requise pour le montage, la protection environnementale, l’alimentation, le calcul, les communications, la référence spatiale, le traitement des données, la maintenabilité terrain, l’intégration au flux de travail et les preuves de validation.",
                "Un « produit de démonstration » est nécessaire avant qu’il soit rationnel de financer un programme complet de productisation.",
                "Plusieurs configurations de démonstration apparentées exigent une stratégie disciplinée distinguant le tronc commun des adaptations spécifiques à l’application.",
            ]),
            ("Offres C et D — étape du produit et de l’exécution", [
                "Un démonstrateur a fonctionné en projet pilote ou en essai terrain, mais le produit n’est pas prêt pour un déploiement reproductible.",
                "Un client important, un distributeur, un investisseur ou un partenaire stratégique exige un plan de commercialisation crédible.",
                "Le matériel doit être robustifié pour les conditions minières avant un déploiement à grande échelle.",
                "Les exigences de certification, de CEM, d’essais environnementaux, de sécurité, de vérification ou de conformité sont floues ou tardives.",
                "Le produit ne peut pas encore être construit, testé, installé, entretenu, soutenu ou configuré de façon fiable au volume visé.",
                "Une petite équipe coordonne trop de fournisseurs sans autorité technique claire, contrôle des interfaces ni critères d’acceptation.",
                "L’entreprise doit passer d’un soutien assuré par les fondateurs à un déploiement reproductible et à une échelle de distribution.",
                "La capacité d’ingénierie interne est insuffisante, mais une organisation complète de développement de produits n’est pas encore justifiable.",
                "Une feuille de route priorisée existe, mais n’a pas été convertie en lots de travail assumés, portées de partenaires, gouvernance et jalons de préparation.",
            ]),
        ],
        "rules_label": "Entrée et progression",
        "rules_h2": "Comment le passage d’une offre à l’autre est encadré.",
        "rules": [
            "L’Offre A définit et fait approuver l’application minière prioritaire et le contexte de démonstration. C’est l’étape de cadrage de l’application.",
            "L’Offre B commence uniquement après l’approbation formelle du livrable de contexte de l’Offre A, ou avec une documentation approuvée équivalente déjà en main.",
            "L’Offre C évalue un démonstrateur ou prototype défini et crée la base de productisation. Elle n’exécute pas les travaux de productisation.",
            "L’Offre D commence uniquement par une proposition ou un énoncé de travaux approuvé séparément, et débute normalement par une phase Surge délimitée.",
            "Le passage de Surge à l’Exécution exige l’autorisation distincte des lots de travail retenus, du modèle de ressources, du financement, de la gouvernance technique et de la structure décisionnelle.",
            "La transition de l’Exécution au Maintien est possible lorsque les lots de travail actifs sont terminés, transférés, suspendus ou réduits à un besoin consultatif.",
            "Une refonte importante, un contexte de déploiement élargi, une nouvelle variante de produit, un problème terrain majeur, un échec de certification, un changement de fournisseur ou une exigence d’échelle du réseau exige normalement une nouvelle phase ou un lot de travail ciblé, plutôt qu’une expansion informelle.",
            "Chaque offre peut se conclure par une recommandation de poursuivre, de restreindre, de pivoter, de suspendre, de valider davantage ou de passer à l’étape suivante. Une recommandation d’arrêter est un résultat légitime.",
        ],
        "fit_label": "Adéquation",
        "fit_h2": "Quand un mandat n’est pas la bonne réponse.",
        "fit_intro": "Être explicite sur les mauvaises adéquations protège les deux parties. Un mandat a peu de chances d’être productif dans les situations suivantes.",
        "fit": [
            "Il n’existe aucune technologie, concept, base de preuves, référence produit crédible ni équipe engagée à évaluer.",
            "La demande porte sur de la main-d’œuvre isolée en CAO, routage de circuits imprimés, micrologiciel, logiciel, documentation ou gestion de projet, sans mandat défini d’application, de démonstrateur, de productisation ou de livraison.",
            "Il n’y a ni commanditaire exécutif, ni décideur, ni voie budgétaire, ni responsable de produit, ni volonté d’agir sur les conclusions.",
            "On s’attend à ce que Spyke Technologies assume une responsabilité de fabricant officiel, de sécurité du produit, réglementaire, de garantie, d’approvisionnement, de réseau commercial ou de performance terrain sans une structure commerciale appropriée négociée séparément.",
            "Un engagement clé en main à prix fixe est exigé avant que la portée technique, les exigences des partenaires, les risques, les critères d’acceptation et les frontières de responsabilité puissent être définis.",
            "Pour l’Offre D, il y a réticence à conserver un accès direct aux relations essentielles de produit, de fournisseurs, d’essais, de fabrication, de déploiement, de service et de distribution.",
        ],
        "net_label": "Réseau de livraison",
        "net_h2": "Un leader senior, plus la capacité spécialisée que l’étape exige.",
        "net_intro": "La contractualisation directe par le client est la norme. Spyke Technologies définit les besoins techniques, les portées, les interfaces, les critères d’acceptation, la gouvernance et les exigences d’intégration, puis évalue le travail des partenaires selon les critères convenus — sans devenir le chemin critique commercial ou opérationnel.",
        "net_head": ("Domaine de capacité", "Rôle de Spyke Technologies", "Contribution typique des partenaires"),
        "net": [
            ("Cadrage d’application minière", "Diriger le cadrage du cas d’usage, la traduction du contexte d’exploitation et la planification de la preuve", "Découverte client menée par le client; apport d’experts si délimité séparément"),
            ("Définition de plateforme de démonstration", "Diriger les exigences système, la définition des interfaces, la stratégie de validation et le cadrage des risques techniques", "Revue spécialisée en détection, optique, robotique, logiciel ou systèmes"),
            ("Architecture produit et feuille de route", "Diriger, intégrer, décider, réviser", "Revue par les pairs spécialisée"),
            ("Robustification et conception pour l’environnement minier", "Diriger la stratégie et les décisions clés", "Boîtiers, thermique, vibration, choc, corrosion et analyses détaillées"),
            ("Conception mécanique et électromécanique", "Orientation, revue, contribution à fort levier", "CAO, mise en plan, dessins, faisceaux et boîtiers"),
            ("Électronique et systèmes embarqués", "Supervision système, exigences, intégration", "Schématique, routage de circuits imprimés, micrologiciel, logiciel, infonuagique et ingénierie de données"),
            ("Certification et validation", "Définir le parcours, préparer, diriger la réponse technique", "Laboratoires accrédités en CEM et essais environnementaux, services d’essais spécialisés"),
            ("Prototypes et conception pour la fabrication", "Exigences, autorité technique, acceptation", "Ateliers de prototypage, fournisseurs EMS, partenaires d’outillage et de fabrication"),
            ("Montée en cadence de fabrication", "Direction de la préparation à la fabrication, coordination technique des fournisseurs", "Fabrication à contrat, qualité, approvisionnement, montages d’essai"),
            ("Déploiement et soutien terrain", "Stratégie de déploiement, escalade, acceptation", "Installateurs régionaux, partenaires de service, soutien sur site"),
            ("Habilitation technique des distributeurs", "Modèle de soutien, formation et exigences de maintenabilité", "Formation du réseau, distribution, ressources de service locales"),
        ],
        "cta_h2": "Identifiez votre point d’entrée.",
        "cta_p": "Décrivez les preuves que vous détenez et la décision devant vous. Si une autre étape est la bonne réponse, on vous le dira.",
        "cta_btn": "Démarrer une conversation",
    },

    # ------------------------------------------------------------- industries
    "industries": {
        "file": "industries.html",
        "title": "Secteurs et applications — Spyke Technologies Inc.",
        "desc": "Profils de clients, domaines technologiques, contextes de déploiement minier et exigences de préparation applicables aux produits industriels déployés en mine.",
        "eyebrow": "Secteurs et applications",
        "h1": "Conçu pour les équipes qui amènent leur technologie en conditions minières.",
        "lead": "Le fil conducteur n’est ni un type de capteur ni un marché unique. C’est un produit industriel qui doit survivre à un environnement minier, s’intégrer à un flux de travail minier et être soutenu longtemps après la démonstration.",
        "who_label": "Qui fait appel",
        "who_h2": "Profils de clients.",
        "who": [
            ("Innovateurs émergents en technologies minières", "Des équipes disposant d’une technologie crédible ou d’un prototype précoce qui ont besoin d’une première application minière ciblée, d’un démonstrateur terrain crédible ou d’une voie vers un déploiement commercial reproductible."),
            ("Entreprises industrielles et OEM", "Des organisations disposant d’une capacité éprouvée dans un secteur voisin qui évaluent le marché minier, ou une unité d’affaires en technologies émergentes préparant une nouvelle gamme de produits."),
            ("Investisseurs, accélérateurs et groupes d’innovation", "Des commanditaires évaluant le risque de marché minier, de démonstrateur, de productisation ou d’exécution d’une société en portefeuille, en amont d’une décision de financement ou de « go/no-go »."),
        ],
        "dom_label": "Domaines technologiques",
        "dom_h2": "Capacités qui entrent régulièrement dans le secteur minier.",
        "dom": [
            ("Détection et mesure industrielles", "Systèmes de perception, de surveillance d’état, de mesure et d’inspection qui doivent conserver leur précision malgré la poussière, les vibrations, les écarts de température et la contamination."),
            ("IA, données et analytique", "Produits d’aide à la décision dont la valeur dépend de la vérité-terrain, de la latence, de l’indication de confiance et d’une voie d’action crédible pour l’opérateur."),
            ("Automatisation et robotique", "Systèmes interagissant avec les équipements, les flux de travail et les personnes, où le contrôle des interfaces, le cadrage de la sécurité et l’autorisation du site déterminent ce qui peut être déployé."),
            ("Communications et connectivité", "Produits de connectivité souterraine et de surface, de télémétrie et de transport de données soumis à des contraintes de référence spatiale, de couverture et de TI/TO."),
            ("Électrification et systèmes de puissance", "Matériel de batterie, de recharge, de conversion et de gestion d’énergie confronté à l’exposition environnementale, à la portée de certification et aux exigences de maintenabilité."),
            ("Technologies environnementales et de sécurité", "Produits de surveillance, de détection et de conformité où la qualité des preuves et les parcours d’approbation orientent la conception."),
        ],
        "ctx_label": "Contexte de déploiement",
        "ctx_h2": "Ce qu’impose l’environnement minier.",
        "ctx_intro": "Les applications minières combinent des exigences d’exposition environnementale, d’installation, d’alimentation, de communications, de données, de sécurité, de maintenabilité, de fiabilité et de soutien à long terme. Un démonstrateur crédible peut prouver une valeur technique sans en établir aucune.",
        "ctx": [
            "Type de mine, procédé ou actif, et zone de travail précise visée",
            "Flux de travail de l’utilisateur, décision opérationnelle soutenue et base de vérité-terrain",
            "Exposition environnementale : poussière, eau, vibration, choc, plage de température, corrosion",
            "Contraintes de montage, d’installation et d’interface avec les équipements",
            "Disponibilité, conditionnement et gestion de l’alimentation",
            "Couverture des communications, télémétrie, référence spatiale et traitement des données",
            "Parcours de sécurité, de TI/TO et d’autorisation de site",
            "Maintenabilité terrain, pièces de rechange, diagnostics et escalade du soutien",
        ],
        "ctx_alt": "Gradins et routes de halage d’une mine à ciel ouvert en plein jour",
        "stake_label": "Parcours d’adoption",
        "stake_h2": "Le mérite technique n’est pas la seule barrière.",
        "stake_intro": "L’adoption minière passe par un ensemble de parties prenantes détenant chacune une forme différente de veto. Les cartographier tôt fait partie du travail de cadrage de l’application.",
        "stake": [
            "Utilisateur opérationnel", "Évaluateur technique", "Responsable de l’entretien", "Partie prenante sécurité",
            "Partie prenante TI/TO", "Champion du site", "Responsable budgétaire", "Approvisionnement",
            "Commanditaire du projet pilote", "Distributeur ou partenaire de service",
        ],
        "cta_h2": "Votre produit affronte-t-il ces conditions?",
        "cta_p": "Si votre technologie doit fonctionner dans une mine et y être soutenue, les questions de préparation sont les mêmes, quel que soit le capteur, l’algorithme ou le marché.",
        "cta_btn": "Démarrer une conversation",
    },

    # ------------------------------------------------------------------ about
    "about": {
        "file": "about.html",
        "title": "À propos — Spyke Technologies Inc.",
        "desc": "Spyke Technologies Inc. est une société-conseil indépendante en technologies minières dirigée par Sandy Pyke, fort de plus de 30 ans en R-D, déploiement et soutien de technologies minières.",
        "eyebrow": "À propos",
        "h1": "Un jugement technique senior, appliqué à l’étape où il compte.",
        "lead": "Spyke Technologies Inc. est une société-conseil indépendante établie dans la région de Montréal, au Québec, qui accompagne des équipes technologiques canadiennes et internationales entrant dans le secteur minier ou s’y développant.",
        "photo_alt": "Sandy Pyke, président de Spyke Technologies Inc.",
        "person_name": "Sandy Pyke",
        "person_role": "Président — Spyke Technologies Inc.",
        "bio_label": "Principal",
        "bio": [
            "Plus de 30 ans en technologies minières, couvrant le développement de produits et de systèmes, le déploiement terrain, le soutien mondial, la préparation à la fabrication ainsi que l’habilitation des concessionnaires et du réseau de distribution.",
            "Une carrière bâtie dans l’équipement minier et les technologies industrielles : électronique et systèmes embarqués, détection industrielle, déploiement de matériel en environnements sévères, et direction technique d’organisations d’ingénierie livrant des produits en production et sur le terrain.",
            "Le constat récurrent de ces années est celui autour duquel cette pratique est bâtie : des technologies performantes arrivent sur un site minier sans la définition d’application, les preuves de démonstrateur ou le travail de productisation requis pour devenir un produit qu’une mine peut acheter, déployer, entretenir et soutenir.",
            "Les mandats se déroulent en français et en anglais, dans un contexte d’exploitation québécois et canadien.",
        ],
        "bg_label": "Parcours",
        "bg_h2": "Domaines de pratique.",
        "bg": [
            "Équipement minier et systèmes de technologies industrielles",
            "Détection industrielle, électronique et matériel embarqué",
            "Architecture produit et système, exigences et contrôle des interfaces",
            "Robustification, validation et planification du parcours de certification",
            "Préparation à la fabrication, testabilité et maintenabilité",
            "Déploiement terrain, service, soutien et habilitation du réseau",
            "Leadership technique, gouvernance et transfert de capacité",
        ],
        "prin_label": "Principes de mandat",
        "prin_h2": "Comment le travail est mené.",
        "prin": [
            ("Axé sur la décision", "Chaque mandat produit une prochaine décision définie, et non un document décrivant une situation que vous connaissiez déjà."),
            ("Les preuves avant l’opinion", "Les constats s’appuient sur votre architecture, vos résultats d’essais, vos observations terrain et votre contexte de déploiement — et sont corrigés lorsque vous les corrigez."),
            ("Transfert de capacité par conception", "Un mandat réussi laisse votre équipe plus capable et moins dépendante. Faire de Spyke Technologies le chemin critique est un mode de défaillance, pas un modèle d’affaires."),
        ],
        "bound_label": "Cadre de travail",
        "bound_h2": "Ce qu’est cette pratique, et ce qu’elle n’est pas.",
        "cta_h2": "Commencez par une conversation.",
        "cta_p": "Confidentielle, sans engagement, et habituellement suffisante pour établir à quelle étape vous vous situez.",
        "cta_btn": "Démarrer une conversation",
    },

    # ---------------------------------------------------------------- contact
    "contact": {
        "file": "contact.html",
        "title": "Contact — Spyke Technologies Inc.",
        "desc": "Amorcez une conversation confidentielle sur votre application minière, votre démonstrateur terrain, votre préparation à la productisation ou votre parcours d’exécution.",
        "eyebrow": "Contact",
        "h1": "Trouvez le bon point de départ.",
        "lead": "Que vous évaluiez une application minière, définissiez un démonstrateur terrain, productisiez un prototype éprouvé ou planifiiez un programme de mise à l’échelle, commencez par une conversation confidentielle sur les preuves que vous détenez et la décision devant vous.",
        "form_label": "Demande",
        "form_h2": "Envoyer un message.",
        "f_name": "Nom",
        "f_company": "Entreprise",
        "f_email": "Courriel",
        "f_stage": "Étape du produit",
        "f_stage_opts": [
            "Sélectionner",
            "Concept ou technologie crédible, sans application minière définie",
            "Technologie éprouvée ou prototype de laboratoire",
            "Démonstrateur fonctionnel ou validé sur le terrain",
            "Feuille de route de productisation approuvée, prêt à exécuter",
            "Autre ou incertain",
        ],
        "f_interest": "Champ d’intérêt",
        "f_interest_opts": [
            "Sélectionner",
            "Offre A — Sprint de cadrage d’application minière",
            "Offre B — Définition de plateforme de démonstration minière",
            "Offre C — Évaluation de productisation prête pour la mine",
            "Offre D — Programme de préparation du prototype au réseau de distribution",
            "Incertain — aidez-moi à trouver le point d’entrée",
        ],
        "f_message": "Sur quoi travaillez-vous?",
        "f_message_ph": "Décrivez brièvement la technologie, les preuves dont vous disposez aujourd’hui et la décision que vous cherchez à prendre.",
        "f_submit": "Envoyer la demande",
        "f_note": "Veuillez ne pas inclure de renseignements confidentiels ou exclusifs dans ce formulaire. Une entente de confidentialité mutuelle peut être mise en place avant toute discussion technique détaillée.",
        "details_label": "Coordonnées",
        "details_h2": "Contact direct.",
        "d_email": "Courriel",
        "d_region": "Région",
        "d_region_v": "Région de Montréal, Québec, Canada",
        "d_languages": "Langues",
        "d_languages_v": "Français et anglais",
        "d_li": "LinkedIn — personnel",
        "d_lic": "LinkedIn — entreprise",
        "next_label": "Prochaines étapes",
        "next_h2": "Un démarrage court et structuré.",
        "next": [
            ("Conversation d’adéquation", "Un appel de 30 minutes pour établir ce qui existe aujourd’hui, ce qui crée l’urgence, qui détient l’autorité décisionnelle et où se situe la véritable incertitude."),
            ("Aiguillage par maturité", "Une recommandation sur le point d’entrée approprié — y compris une recommandation de ne pas poursuivre, si c’est la réponse honnête."),
            ("Proposition délimitée", "S’il y a adéquation, une proposition à portée fixe précisant les hypothèses, les intrants du client, les livrables, les critères d’acceptation et les exclusions."),
        ],
    },

    # ------------------------------------------------------------------- 404
    "notfound": {
        "file": "404.html",
        "title": "Page introuvable — Spyke Technologies Inc.",
        "desc": "La page demandée est introuvable.",
        "eyebrow": "404",
        "h1": "Cette page est introuvable.",
        "lead": "Le lien est peut-être périmé. Les pages ci-dessous couvrent les offres, le parcours et les coordonnées.",
        "back": "Retourner à l’accueil",
    },
}
