# -*- coding: utf-8 -*-
"""English site content for Spyke Technologies Inc.

Edit copy here, then run `python3 build.py` to regenerate every page.
No pricing, rates, capacity caps, client names or contractual terms appear
in this file by design. Keep it that way.
"""

C = {
    # ------------------------------------------------------------------ chrome
    "lang": "en",
    "lang_name": "English",
    "other_lang": "fr",
    "other_lang_label": "FR",
    "other_lang_aria": "Passer au français",
    "skip": "Skip to main content",
    "dir_prefix": "",
    "nav": [
        ("offers.html", "Offers"),
        ("pathway.html", "Pathway"),
        ("industries.html", "Industries"),
        ("about.html", "About"),
    ],
    "nav_cta": ("contact.html", "Start a conversation"),
    "nav_open": "Open navigation menu",
    "nav_close": "Close navigation menu",
    "theme_to_dark": "Switch to dark mode",
    "theme_to_light": "Switch to light mode",
    "home_label": "Spyke Technologies Inc. — home",
    "breadcrumb_home": "Home",
    "footer_tagline": "Mining application definition, demonstration platforms, productization and scale-up.",
    "footer_nav_title": "Site",
    "footer_offers_title": "Offers",
    "footer_contact_title": "Contact",
    "footer_legal": "© {year} Spyke Technologies Inc. All rights reserved.",
    "footer_location": "Montréal region, Quebec, Canada",
    "footer_note": "Independent consulting based on general professional experience, independent analysis and publicly available information.",
    "li_personal_label": "Sandy Pyke on LinkedIn",
    "li_company_label": "Spyke Technologies on LinkedIn",
    "fig": "Fig.",

    # short offer labels reused across the site
    "offers_meta": [
        {
            "slug": "offer-a-mining-application-framing-sprint.html",
            "tag": "Offer A",
            "name": "Mining Application Framing Sprint",
            "short": "Define the right mine problem before you build.",
            "stage": "Define the mine problem",
            "question": "Where can this technology create practical value in mining, and what must a first demonstrator prove?",
            "start": "Credible technology or concept; no sufficiently defined mining application or demonstration context.",
            "outcome": "Chosen mining use case and demonstration context, stakeholder and adoption map, proof plan, and a 90-day validation roadmap.",
            "duration": "1–2 weeks of effort, normally within 2–3 calendar weeks.",
            "img": "application-framing.webp",
            "alt": "Open-pit mine at blue hour with haul roads descending into the pit",
        },
        {
            "slug": "offer-b-mining-demonstration-platform-definition.html",
            "tag": "Offer B",
            "name": "Mining Demonstration Platform Definition",
            "short": "Specify the field demonstrator a mine customer can actually evaluate.",
            "stage": "Build the proof",
            "question": "What demonstrator should we build, what mine workflow must it support, and what evidence must it produce?",
            "start": "Tested technology or early prototype; approved application and demonstration context.",
            "outcome": "Field-deployable demonstration platform specification, modular configuration and interface definition, validation plan, traceability matrix, risk register and executive build decision package.",
            "duration": "Normally 5–7 calendar weeks after the context is approved; combined A + B normally 7–10 calendar weeks.",
            "img": "field-demonstrator.webp",
            "alt": "Ruggedized instrumentation enclosure mounted on the machine-house roof of an open-pit mining shovel, inboard of the handrail and clear of the working envelope",
        },
        {
            "slug": "offer-c-mine-ready-productization-assessment.html",
            "tag": "Offer C",
            "name": "Mine-Ready Productization Assessment",
            "short": "Make the gap between a demonstrator and a commercial product visible.",
            "stage": "Productize for the mine",
            "question": "What must change before the demonstrator can be validated, manufactured, installed, serviced, supported and scaled?",
            "start": "Defined application and a representative working or field-validated demonstrator or prototype.",
            "outcome": "Evidence-based productization baseline, scorecard, prioritized gap register, demonstrator-to-product transition view, indicative 18–24 month roadmap and a recommended execution model.",
            "duration": "Up to 4 calendar weeks, remote-first.",
            "img": "productization-bench.webp",
            "alt": "Electronics bench with instrumentation and a partially assembled industrial enclosure",
        },
        {
            "slug": "offer-d-prototype-to-channel-readiness-program.html",
            "tag": "Offer D",
            "name": "Prototype-to-Channel Readiness Program",
            "short": "Turn an approved roadmap into governed execution and client-owned capability.",
            "stage": "Scale with confidence",
            "question": "How do we convert the roadmap into an executable program and build the delivery capability required for scale?",
            "start": "Approved productization baseline or equivalent evidence, executive sponsor, funding path and a named product owner.",
            "outcome": "Governed execution plan, high-leverage technical leadership, partner technical coordination, readiness-gate progress and capability transfer.",
            "duration": "Surge normally 2–6 months; Execute normally 6–18 months; Maintenance ongoing.",
            "img": "channel-readiness.webp",
            "alt": "Row of identical ruggedized equipment enclosures on an assembly bench",
        },
    ],

    "stages": [
        ("Define the mine problem", "Offer A", "Is this the right mining application and demonstration context to pursue?"),
        ("Build the proof", "Offer B", "What field-deployable demonstrator should be built, and what evidence must it produce?"),
        ("Productize for the mine", "Offer C", "What must change before the demonstrator can become a repeatable commercial product?"),
        ("Scale with confidence", "Offer D", "How do we execute the work and build the delivery capability required for scale?"),
    ],

    # ------------------------------------------------------------------- home
    "home": {
        "file": "index.html",
        "title": "Spyke Technologies Inc. — Mining technology application, demonstration and productization",
        "desc": "Spyke Technologies helps qualified technology teams define the right mining application, specify field-deployable demonstrators, assess productization readiness and lead the work required to scale a mine-ready product.",
        "hero_eyebrow": "Mining technology consulting",
        "hero_h1_a": "From mining application to field demonstrator to a ",
        "hero_h1_accent": "mine-ready, channel-ready product.",
        "hero_sub": "Spyke Technologies Inc. helps qualified technology teams define the right mining application before building, specify field-deployable demonstrators, assess productization readiness, and lead the ruggedization, validation, manufacturing-readiness, deployment and service work required to scale.",
        "hero_cta1": "Find your starting point",
        "hero_cta2": "See the four offers",
        "hero_alt": "Underground mine drift lit by equipment lights",
        "stats": [
            ("Experience", "30+ years", "Mining technology R&D, deployment and support"),
            ("Structure", "4 staged offers", "Each with its own entry point and exit decision"),
            ("Model", "One senior lead", "Plus the delivery capacity your stage requires"),
            ("Based in", "Montréal, QC", "Serving Canadian and international teams"),
        ],
        "pos_label": "Point of view",
        "pos_h2": "A working prototype is not the summit. It is base camp.",
        "pos_p1": "Many technologies look promising in a laboratory, a pilot, or an adjacent industry. Mining adoption depends on more: the technology has to solve a real operational problem, fit the mine workflow, be demonstrated credibly in the field, and then mature into a product that can survive, be validated, manufactured, installed, serviced, supported and scaled.",
        "pos_p2": "Mining technology teams get stuck on what we call Approval Mountain. Each customer requirement, site constraint, field observation, certification need, manufacturing limitation, service requirement or distributor expectation reveals another readiness gate. The fastest way to build the wrong mining product is to start with the technology instead of the mine problem, the operating context, and the proof required.",
        "pos_note": "Approval Mountain is a communication framework, not a claim of control over third-party approvals.",
        "stages_label": "The pathway",
        "stages_h2": "Define the mine problem. Build the proof. Productize for the mine. Scale with confidence.",
        "stages_intro": "Four stages, four offers. Each begins from a distinct evidence base, answers a different question and produces a defined next decision. They are complementary — not lower-cost slices of the same engagement.",
        "stages_decision": "Decision enabled",
        "offers_label": "Offers",
        "offers_h2": "Start at the stage that matches your evidence.",
        "offers_intro": "You do not start at a predetermined service level. You start where your evidence, your product maturity and your next decision actually are.",
        "offers_more": "Read the full offer",
        "route_label": "Entry points",
        "route_h2": "Not sure where you belong?",
        "route_intro": "Maturity routing is deliberate. The table below matches the uncertainty you are carrying today to the offer designed to resolve it.",
        "route_head": ("Your situation today", "Primary uncertainty", "Offer"),
        "route_cta": "See the full pathway and progression rules",
        "readiness_label": "Readiness domains",
        "readiness_h2": "Mine-readiness is assessed across seven domains.",
        "readiness_intro": "A demonstrator can prove valuable technical capability and still be years away from repeatable deployment. These are the domains examined in a Mine-Ready Productization Assessment.",
        "readiness": [
            "Product and system architecture",
            "Mine environment and ruggedization",
            "Embedded, application, cloud, data and communications readiness",
            "Verification, validation, certification and compliance path",
            "Manufacturability, testability and supply-chain readiness",
            "Deployment, service and lifecycle support",
            "Channel and execution readiness",
        ],
        "delivery_label": "Delivery model",
        "delivery_h2": "One technical lead. The right delivery capacity.",
        "delivery_p1": "Spyke Technologies provides senior mining-technology product leadership where it creates the most value: mine-operational translation, requirements and interface definition, productization strategy, technical integration, readiness-gate leadership, risk reduction, partner coordination and capability transfer.",
        "delivery_p2": "Detailed implementation work is performed by your team or by qualified specialists where appropriate. Client-direct contracting with engineering firms, laboratories, manufacturers, installers, service providers and channel partners is the default — so the engagement does not become the critical path, and you are left more capable rather than more dependent.",
        "delivery_alt": "Engineers reviewing technical drawings during a design review",
        "bound_label": "Working boundaries",
        "bound_h2": "Clear responsibilities.",
        "bound_p1": "You retain product ownership, commercial decisions, customer relationships, expenditures, direct supplier and partner relationships wherever practical, final product-release authority, and manufacturer-of-record responsibility.",
        "bound_p2": "Spyke Technologies is not generic strategy consulting, a staffing agency, a contract manufacturer, a system integrator of record, a certification laboratory or body, a sales-representation service, or a substitute for your manufacturer-of-record responsibilities. No engagement guarantees mine-site access, customer approval, pilot sponsorship, certification, market fit or commercial success.",
        "bound_p3": "Spyke Technologies provides independent consulting based on general professional experience, independent analysis and publicly available information. Confidential, proprietary or trade-secret information belonging to any current or former employer, client, supplier or partner is not used, disclosed or made accessible.",
        "cta_h2": "Start with the evidence you have.",
        "cta_p": "A short, confidential conversation is usually enough to identify which stage you are at and which decision comes next.",
        "cta_btn": "Start a conversation",
    },

    # ----------------------------------------------------------------- offers
    "offers": {
        "file": "offers.html",
        "title": "Offers — Spyke Technologies Inc.",
        "desc": "Four staged offers: Mining Application Framing Sprint, Mining Demonstration Platform Definition, Mine-Ready Productization Assessment, and the Prototype-to-Channel Readiness Program.",
        "eyebrow": "Offers",
        "h1": "Four offers. One maturity path.",
        "lead": "Each offer begins from a distinct evidence base, answers a different client question, has a deliberate boundary, and produces a defined next decision. Completion of one offer does not oblige either party to enter the next.",
        "table_label": "At a glance",
        "table_head": ("Offer", "Starting point", "Question answered", "Primary outcome", "Typical duration"),
        "cards_label": "The offers",
        "cards_h2": "What each engagement produces.",
        "detail_more": "Full offer detail",
        "detail_best": "Best for",
        "detail_out": "Primary outcome",
        "rules_label": "Progression",
        "rules_h2": "How offers connect.",
        "rules": [
            "A team with credible technology but no defined mining application normally begins with Offer A.",
            "Offer B begins after Offer A is approved, or when equivalent documented and client-approved application and demonstration context already exists.",
            "Offers A and B may be sold together as one milestone-gated engagement, with a formal context-approval gate between them.",
            "A team with a defined application and a representative working demonstrator may begin directly at Offer C.",
            "A team with a completed productization baseline may be considered directly for Offer D, subject to fit and scope validation.",
            "Offer D normally begins with a scoped Surge phase; progression to Execute requires separate client authorization.",
            "Progression is based on evidence, maturity, readiness, decision authority and separately approved scope — never on an automatic upsell.",
            "One offer is never allowed to substitute for required work in the next maturity stage.",
        ],
        "cta_h2": "Which offer fits your evidence?",
        "cta_p": "If the answer is not obvious, the pathway page sets out the routing logic, trigger events and fit criteria in detail.",
        "cta_btn": "Start a conversation",
        "cta_btn2": "See the pathway",
    },

    # ---------------------------------------------------------------- pathway
    "pathway": {
        "file": "pathway.html",
        "title": "Pathway and entry points — Spyke Technologies Inc.",
        "desc": "Maturity routing, trigger events, entry and progression rules, and fit criteria for Spyke Technologies mining technology engagements.",
        "eyebrow": "Pathway",
        "h1": "Where you enter depends on the evidence you already have.",
        "lead": "Mining technology teams arrive at very different points: an unproven market hypothesis, a laboratory prototype, a demonstrator that worked in a field trial, or an approved roadmap waiting for execution. The entry point should match the uncertainty, not a service tier.",
        "chain_label": "Value chain",
        "chain_h2": "Four stages, four decisions.",
        "chain_head": ("Stage", "Offer", "Client decision enabled"),
        "route_label": "Maturity routing",
        "route_h2": "Match your situation to an entry point.",
        "route_head": ("Client situation", "Primary uncertainty", "Appropriate offer"),
        "routes": [
            ("Credible technology or concept, but no narrow mining problem, target workflow, demonstration context or proof objective",
             "Where should this technology create practical value in mining, and what must it prove first?",
             "Offer A", "offer-a-mining-application-framing-sprint.html"),
            ("Tested technology, laboratory prototype or early system; approved or credible candidate context; no requirements-level demonstrator definition",
             "What demonstrator should we build, what workflow must it support, and what evidence must it produce?",
             "Offer B", "offer-b-mining-demonstration-platform-definition.html"),
            ("Representative demonstrator or prototype exists for a defined mining application, but repeatable product deployment is uncertain",
             "What must change before the system can be validated, manufactured, installed, serviced, supported and scaled?",
             "Offer C", "offer-c-mine-ready-productization-assessment.html"),
            ("Productization roadmap or equivalent evidence exists; sponsorship, funding path, decision authority and readiness to execute are in place",
             "How do we convert the roadmap into an executable program and build the capability required for scalable deployment?",
             "Offer D", "offer-d-prototype-to-channel-readiness-program.html"),
        ],
        "trig_label": "Trigger events",
        "trig_h2": "Signals that it is time to start.",
        "trig_groups": [
            ("Offer A — application stage", [
                "A capability proven in another sector — sensing, AI, automation, communications, electrification, environmental technology, robotics or data systems — is being considered for mining.",
                "A founder, investor, accelerator, incubator, OEM or innovation group is asking where the technology could create practical value in mining.",
                "Several plausible mining applications exist but the team cannot confidently select the first one.",
                "A first mine-relevant demonstrator is about to be funded, and the team wants to avoid designing around an assumed use case.",
                "An early customer or mining contact has expressed interest, but the request is too broad or contradictory to become a development mandate.",
                "The team understands its technology but not mine workflows, equipment interfaces, operating constraints, maintenance expectations, buyer roles or site-access realities.",
                "A credible mining use-case narrative is needed for an investor discussion, grant application, partner conversation or internal go/no-go review.",
            ]),
            ("Offer B — demonstrator stage", [
                "Tested technology needs to be shown credibly inside a mining workflow.",
                "A laboratory system, tripod-mounted sensor, adapted industrial product or pilot configuration does not yet constitute a field-deployable demonstration platform.",
                "A prospective mine site is interested, but a practical system definition is needed before committing to a build.",
                "The target application and demonstration context are approved or already sufficiently documented.",
                "Requirements-level definition is needed for mounting, environmental protection, power, compute, communications, spatial reference, data handling, field serviceability, workflow integration and validation evidence.",
                "A “demo product” is needed before it is rational to fund a full productization program.",
                "Several related demonstration configurations need a disciplined common-core versus application-specific adaptation strategy.",
            ]),
            ("Offers C and D — product and execution stage", [
                "A demonstrator worked in a pilot or field trial, but the product is not ready for repeatable deployment.",
                "A major customer, distributor, investor or strategic partner requires a credible commercialization plan.",
                "Hardware must be ruggedized for mine conditions before broad deployment.",
                "Certification, EMC, environmental testing, safety, verification or compliance requirements are unclear or late.",
                "The product cannot yet be built, tested, installed, serviced, supported or configured reliably at the intended volume.",
                "A small team is coordinating too many suppliers without clear technical authority, interface control or acceptance criteria.",
                "The company needs to move from founder-led support toward repeatable deployment and distributor scale.",
                "Internal engineering capacity is insufficient, but a complete product-development organization cannot yet be justified.",
                "A prioritized roadmap exists but has not been turned into owned work packages, partner scopes, governance and readiness gates.",
            ]),
        ],
        "rules_label": "Entry and progression",
        "rules_h2": "How movement between offers is governed.",
        "rules": [
            "Offer A defines and obtains approval of the priority mining application and demonstration context. It is the application-framing stage.",
            "Offer B begins only after formal approval of the Offer A context deliverable, or with equivalent approved documentation already in hand.",
            "Offer C evaluates a defined demonstrator or prototype and creates the productization baseline. It does not perform managed productization work.",
            "Offer D begins only through a separately approved proposal or statement of work, and normally starts with a scoped Surge phase.",
            "Progression from Surge to Execute requires separate authorization of the selected work packages, resource model, funding, technical governance and decision structure.",
            "A transition from Execute to Maintenance is available when active work packages are complete, handed off, paused or reduced to an advisory need.",
            "A material redesign, expanded deployment context, new product variant, major field issue, certification failure, supplier transition or channel-scale requirement normally requires a new phase or targeted work package rather than informal expansion.",
            "Each offer may conclude with proceed, narrow, pivot, pause, further-validation or next-stage recommendations. A recommendation to stop is a legitimate outcome.",
        ],
        "fit_label": "Fit",
        "fit_h2": "Where an engagement is not the right answer.",
        "fit_intro": "Being explicit about poor fit protects both sides. An engagement is unlikely to be productive when any of the following applies.",
        "fit": [
            "There is no credible technology, concept, evidence base, product baseline or committed team to evaluate.",
            "The request is for isolated CAD, PCB routing, firmware, software, documentation or project-management labour without a defined application, demonstrator, productization or delivery mandate.",
            "There is no executive sponsor, decision maker, budget pathway, product owner, or willingness to act on the conclusions.",
            "There is an expectation that Spyke Technologies will accept manufacturer-of-record, product-safety, regulatory, warranty, procurement, commercial-channel or field-performance liability without an appropriate, separately negotiated commercial structure.",
            "A fixed-price turnkey product-development commitment is required before technical scope, partner requirements, risk, acceptance criteria and responsibility boundaries can be defined.",
            "For Offer D, there is unwillingness to retain direct access to essential product, supplier, test, manufacturing, deployment, service and channel relationships.",
        ],
        "net_label": "Delivery network",
        "net_h2": "One senior lead, plus the specialist capacity the stage requires.",
        "net_intro": "Client-direct contracting is the default. Spyke Technologies defines technical needs, scopes, interfaces, acceptance criteria, governance and integration requirements, and reviews partner output against agreed criteria — without becoming the commercial or operational critical path.",
        "net_head": ("Capability area", "Spyke Technologies role", "Typical partner contribution"),
        "net": [
            ("Mining application framing", "Lead use-case framing, operating-context translation and proof planning", "Client-led customer discovery; selected subject-matter input if separately scoped"),
            ("Demonstration platform definition", "Lead system requirements, interface definition, validation strategy and technical risk framing", "Specialist sensing, optics, robotics, software or systems review"),
            ("Product architecture and roadmap", "Lead, integrate, decide, review", "Specialist peer review"),
            ("Ruggedization and mine-environment design", "Lead strategy and key decisions", "Enclosure, thermal, vibration, shock, corrosion and detailed analysis"),
            ("Mechanical and electro-mechanical design", "Direction, review, high-leverage contribution", "CAD, detailing, drawings, harness and enclosure design"),
            ("Electronics and embedded systems", "System oversight, requirements, integration", "Schematic capture, PCB layout, firmware, software, cloud and data engineering"),
            ("Certification and validation", "Define path, prepare, lead technical response", "Accredited EMC and environmental laboratories, specialty test services"),
            ("Prototype builds and DFM", "Requirements, technical authority, acceptance", "Prototype shops, EMS providers, tooling and manufacturing partners"),
            ("Manufacturing scale-up", "Manufacturing-readiness leadership, technical supplier coordination", "Contract manufacturing, quality, sourcing, test-fixture services"),
            ("Field deployment and support", "Deployment strategy, escalation, acceptance", "Regional installers, service partners, site support"),
            ("Distributor technical enablement", "Support model, training and serviceability inputs", "Channel training, distribution, localized service resources"),
        ],
        "cta_h2": "Identify your entry point.",
        "cta_p": "Describe the evidence you have and the decision in front of you. If a different stage is the right answer, you will be told so.",
        "cta_btn": "Start a conversation",
    },

    # ------------------------------------------------------------- industries
    "industries": {
        "file": "industries.html",
        "title": "Industries and applications — Spyke Technologies Inc.",
        "desc": "Client profiles, technology domains, mining deployment contexts and the readiness requirements that apply to mine-deployed industrial products.",
        "eyebrow": "Industries & applications",
        "h1": "Built for teams taking technology into mining conditions.",
        "lead": "The common thread is not a single sensor type or market. It is an industrial product that must survive a mine environment, integrate with a mine workflow, and be supported long after the demonstration.",
        "who_label": "Who engages",
        "who_h2": "Client profiles.",
        "who": [
            ("Emerging mining-technology innovators", "Teams with a credible technology or early prototype that need a focused first mining application, a credible field demonstrator, or a path to repeatable commercial deployment."),
            ("Industrial technology companies and OEMs", "Organizations with a proven capability in an adjacent sector evaluating mining as a market, or an emerging-technology business unit preparing a new product line."),
            ("Investors, accelerators and innovation groups", "Sponsors assessing mining-market, demonstrator, productization or execution risk in a portfolio company, ahead of a funding or go/no-go decision."),
        ],
        "dom_label": "Technology domains",
        "dom_h2": "Capability areas that routinely enter mining.",
        "dom": [
            ("Industrial sensing and measurement", "Perception, condition monitoring, measurement and inspection systems that must hold accuracy through dust, vibration, temperature swings and contamination."),
            ("AI, data and analytics systems", "Decision-support and analytics products whose value depends on ground truth, latency, confidence indication and a credible action pathway for the operator."),
            ("Automation and robotics", "Systems that interact with equipment, workflows and people, where interface control, safety framing and site authorization govern what can be deployed."),
            ("Communications and connectivity", "Underground and surface connectivity, telemetry and data-transport products subject to spatial reference, coverage and IT/OT constraints."),
            ("Electrification and power systems", "Battery, charging, power-conversion and energy-management hardware facing environmental exposure, certification scope and serviceability requirements."),
            ("Environmental and safety technology", "Monitoring, detection and compliance-oriented products where evidence quality and approval pathways drive the design."),
        ],
        "ctx_label": "Deployment context",
        "ctx_h2": "What the mine environment imposes.",
        "ctx_intro": "Mining applications combine environmental exposure, installation, power, communications, data, safety, maintainability, reliability and long-term support requirements. A credible demonstrator can prove technical value without establishing any of them.",
        "ctx": [
            "Mine type, process or asset, and the specific work area being targeted",
            "User workflow, the operational decision being supported, and the ground-truth basis for it",
            "Environmental exposure: dust, water, vibration, shock, temperature range, corrosion",
            "Mounting, installation and equipment-interface constraints",
            "Power availability, conditioning and management",
            "Communications coverage, telemetry, spatial reference and data handling",
            "Safety, IT/OT and site authorization pathways",
            "Field serviceability, spares, diagnostics and support escalation",
        ],
        "ctx_alt": "Open-pit mine benches and haul roads under daylight",
        "stake_label": "Adoption path",
        "stake_h2": "Technical merit is not the only gate.",
        "stake_intro": "Mining adoption runs through a set of stakeholders who each hold a different form of veto. Mapping them early is part of the application-framing work.",
        "stake": [
            "Operational user", "Technical evaluator", "Maintenance owner", "Safety stakeholder",
            "IT/OT stakeholder", "Site champion", "Budget owner", "Procurement",
            "Pilot or demonstration sponsor", "Distributor or service partner",
        ],
        "cta_h2": "Does your product face these conditions?",
        "cta_p": "If your technology has to work in a mine and be supported there, the readiness questions are the same regardless of the sensor, the algorithm or the market.",
        "cta_btn": "Start a conversation",
    },

    # ------------------------------------------------------------------ about
    "about": {
        "file": "about.html",
        "title": "About — Spyke Technologies Inc.",
        "desc": "Spyke Technologies Inc. is an independent mining technology consultancy led by Sandy Pyke, with more than 30 years in mining technology R&D, deployment and support.",
        "eyebrow": "About",
        "h1": "Senior mining-technology judgment, applied at the stage where it matters.",
        "lead": "Spyke Technologies Inc. is an independent consultancy based in the Montréal region of Quebec, working with Canadian and international technology teams entering or scaling in mining.",
        "photo_alt": "Sandy Pyke, President of Spyke Technologies Inc.",
        "person_name": "Sandy Pyke",
        "person_role": "President — Spyke Technologies Inc.",
        "bio_label": "Principal",
        "bio": [
            "More than 30 years in mining technology, spanning product and system development, field deployment, global support, manufacturing readiness, and dealer and channel enablement.",
            "Career built in mining equipment and industrial technology: electronics and embedded systems, industrial sensing, hardware deployment in harsh environments, and the technical leadership of engineering organizations delivering products into production and the field.",
            "The recurring pattern across those years is the same one this practice is built around: capable technology arriving at a mine site without the application definition, the demonstrator evidence, or the productization work required to become something a mine can buy, deploy, service and support.",
            "Work is conducted in English and French, with a Quebec and Canadian operating context.",
        ],
        "bg_label": "Background",
        "bg_h2": "Practice areas.",
        "bg": [
            "Mining equipment and industrial technology systems",
            "Industrial sensing, electronics and embedded hardware",
            "Product and system architecture, requirements and interface control",
            "Ruggedization, validation and certification-path planning",
            "Manufacturing readiness, testability and serviceability",
            "Field deployment, service, support and channel enablement",
            "Technical leadership, governance and capability transfer",
        ],
        "prin_label": "Engagement principles",
        "prin_h2": "How the work is run.",
        "prin": [
            ("Decision-focused", "Every engagement produces a defined next decision, not a document that describes the situation you already knew you were in."),
            ("Evidence before opinion", "Findings are grounded in your architecture, test results, field observations and deployment context — and corrected when you correct them."),
            ("Capability transfer by design", "A successful engagement leaves your team more capable and less dependent. Making Spyke Technologies the critical path is a failure mode, not a business model."),
        ],
        "bound_label": "Working boundaries",
        "bound_h2": "What this practice is, and is not.",
        "cta_h2": "Start with a conversation.",
        "cta_p": "Confidential, no obligation, and usually enough to establish which stage you are at.",
        "cta_btn": "Start a conversation",
    },

    # ---------------------------------------------------------------- contact
    "contact": {
        "file": "contact.html",
        "title": "Contact — Spyke Technologies Inc.",
        "desc": "Start a confidential conversation about your mining application, field demonstrator, productization readiness or execution path.",
        "eyebrow": "Contact",
        "h1": "Find the right starting point.",
        "lead": "Whether you are evaluating a mining application, defining a field demonstrator, productizing a proven prototype or planning a scale-up program, start with a confidential conversation about the evidence you have and the decision in front of you.",
        "form_label": "Enquiry",
        "form_h2": "Send a note.",
        "f_name": "Name",
        "f_company": "Company",
        "f_email": "Email",
        "f_stage": "Product stage",
        "f_stage_opts": [
            "Select one",
            "Concept or credible technology, no defined mining application",
            "Tested technology or laboratory prototype",
            "Working or field-validated demonstrator",
            "Approved productization roadmap, ready to execute",
            "Other or not sure",
        ],
        "f_interest": "Area of interest",
        "f_interest_opts": [
            "Select one",
            "Offer A — Mining Application Framing Sprint",
            "Offer B — Mining Demonstration Platform Definition",
            "Offer C — Mine-Ready Productization Assessment",
            "Offer D — Prototype-to-Channel Readiness Program",
            "Not sure — help me find the entry point",
        ],
        "f_message": "What are you working on?",
        "f_message_ph": "Briefly describe the technology, the evidence you have today, and the decision you are trying to make.",
        "f_submit": "Send enquiry",
        "f_note": "Please do not include confidential or proprietary information in this form. A mutual NDA can be put in place before any detailed technical discussion.",
        "details_label": "Details",
        "details_h2": "Direct contact.",
        "d_email": "Email",
        "d_region": "Region",
        "d_region_v": "Montréal region, Quebec, Canada",
        "d_languages": "Languages",
        "d_languages_v": "English and French",
        "d_li": "LinkedIn — personal",
        "d_lic": "LinkedIn — company",
        "next_label": "What happens next",
        "next_h2": "A short, structured start.",
        "next": [
            ("Fit conversation", "A 30-minute call to establish what exists today, what is driving urgency, who holds decision authority, and where the real uncertainty sits."),
            ("Maturity routing", "A recommendation on the appropriate entry point — including a recommendation not to proceed, if that is the honest answer."),
            ("Scoped proposal", "If there is a fit, a fixed-scope proposal with stated assumptions, client inputs, deliverables, acceptance criteria and exclusions."),
        ],
    },

    # ------------------------------------------------------------------- 404
    "notfound": {
        "file": "404.html",
        "title": "Page not found — Spyke Technologies Inc.",
        "desc": "The requested page could not be found.",
        "eyebrow": "404",
        "h1": "That page could not be found.",
        "lead": "The link may be out of date. The pages below cover the offers, the pathway and how to get in touch.",
        "back": "Return to the home page",
    },
}
