# -*- coding: utf-8 -*-
"""English detail content for Offers A–D."""

OFFERS = {
    # ---------------------------------------------------------------- OFFER A
    "a": {
        "title": "Offer A — Mining Application Framing Sprint | Spyke Technologies Inc.",
        "desc": "A focused sprint that selects the priority mining application, defines the demonstration context, maps adoption stakeholders and produces a 90-day validation roadmap.",
        "eyebrow": "Offer A",
        "h1": "Before you build for mining, define the right mine problem.",
        "lead": "A short, structured sprint for teams with credible technology and no sufficiently defined mining application. It converts a broad technology capability into one prioritized mining use case, an approved demonstration context, and a proof plan that can be funded.",
        "cta_primary": "Define your mining application",
        "purpose_label": "Purpose",
        "purpose_h2": "What this sprint answers.",
        "purpose_q": "Where can this technology create practical value in mining, and what must a first mine-relevant demonstrator prove?",
        "purpose_p": "The fastest way to build the wrong mining product is to design around an assumed use case. This sprint establishes the use case, the operating context, the stakeholders who can approve or block adoption, and the evidence a first demonstrator has to produce — before engineering budget is committed.",
        "entry_label": "Fit",
        "entry_h2": "Entry criteria.",
        "entry": [
            "A credible technology, capability or concept — proven in a laboratory, a pilot, or an adjacent industry.",
            "No sufficiently defined mining application, target workflow, demonstration context or proof objective.",
            "A single technology platform or product family, and no more than three candidate mining applications.",
            "An executive sponsor and a willingness to act on the recommendation, including a recommendation to narrow or pause.",
        ],
        "work_label": "Method",
        "work_h2": "Workstreams.",
        "work": [
            ("Technology and evidence review", "Establish a shared, evidence-based understanding of current capability, credible differentiators, limitations and constraints, using available technical descriptions, demonstrations, architecture information and prior deployment learning."),
            ("Mining opportunity framing", "Identify and compare candidate mining applications against operational value, evidence availability, demonstration feasibility, adoption friction and deployment realism."),
            ("Operating-context translation", "Translate the selected application into mine reality: work area, user workflow, operational decision supported, environmental exposure, installation and interface constraints, power, communications, data and site-authorization considerations."),
            ("Stakeholder and adoption mapping", "Identify operational users, technical evaluators, maintenance and safety stakeholders, IT/OT, site champions, sponsors, budget owners and procurement — and the evidence each needs. Direct external interviews are not included unless separately scoped."),
            ("Demonstrator and proof planning", "Define what a first mine-relevant demonstrator must prove, what is intentionally out of scope for it, and the validation sequence over the following 90 days."),
        ],
        "deliv_label": "Deliverables",
        "deliv_h2": "What you receive.",
        "deliv": [
            ("Mining Opportunity Map", "Candidate applications compared, with a recommended primary use case, an optional secondary, and explicitly deferred or excluded applications."),
            ("Demonstration Context Definition Brief", "The mine type, work area, workflow, operating conditions and constraints that will drive the first demonstrator."),
            ("Stakeholder and Adoption Map", "Who influences adoption, what role each plays, and the evidence each will require."),
            ("Mine Environment and Demonstration Considerations Brief", "Environmental exposure, installation, power, communications, data, safety and site-authorization realities that shape a credible demonstration."),
            ("Demonstrator Decision Brief", "What a first demonstrator must prove, what it must not attempt, and the decision criteria for proceeding."),
            ("Client-Led Discovery Question Set", "A structured question set your team uses in its own customer and mine conversations."),
            ("90-Day Validation Roadmap", "A sequenced plan of validation activities, owners and evidence thresholds."),
            ("Executive readout", "A working session covering the recommendation, the rationale, and the next decision."),
        ],
        "out_label": "Boundaries",
        "out_h2": "Explicitly out of scope.",
        "out": [
            "More than one technology platform, or a broad market study across unrelated mining segments.",
            "Detailed market sizing, forecasts, competitive intelligence, pricing strategy or final product-market strategy.",
            "Direct interviews with mine operators, customers, OEMs, dealers, distributors, investors, partners or regulators.",
            "Guaranteed customer introductions, mine-site access, pilot sponsorship, purchase orders, investment, grant approval, regulatory approval or certification.",
            "Site visits, mine visits, travel, onsite workshops, field trials, installation surveys or environmental measurements.",
            "Offer B deliverables: system requirements specification, modular configuration and interface definition, or a detailed validation and customer-demonstration plan.",
            "Detailed engineering: CAD, schematics, PCB layout, firmware, application or cloud development, prototype construction, detailed bills of material or test execution.",
            "Formal EMC, environmental, safety, functional-safety, cybersecurity, regulatory, certification, product-liability, tax, legal, insurance or manufacturer-of-record analysis or opinion.",
            "Procurement, partner contracting, supplier qualification, commercial negotiation, sales representation or management of third-party work.",
        ],
        "deliv_model_label": "Delivery",
        "deliv_model_h2": "How it runs.",
        "deliv_model": [
            ("Duration", "1–2 weeks of concentrated effort, normally completed within 2–3 calendar weeks of the kickoff and receipt of client inputs."),
            ("Mode", "Remote-first, with a structured kickoff, working sessions and an executive readout."),
            ("Commercial model", "Fixed scope, fixed fee, with stated assumptions, client inputs, acceptance criteria and exclusions set out in the proposal."),
            ("Client inputs", "Technology description and available evidence, any customer or mine contacts and learning to date, sponsor availability, and timely review of draft deliverables."),
        ],
        "next_label": "Next decision",
        "next_h2": "What the sprint enables.",
        "next_p": "A funded, well-aimed demonstrator — or a documented decision to narrow, pivot, validate further, or stop. A recommendation to stop is a legitimate outcome. Where the team proceeds, the approved demonstration context becomes the entry condition for Offer B.",
        "next_link_label": "Continue to Offer B",
        "next_link": "offer-b-mining-demonstration-platform-definition.html",
        "combo": "Offers A and B may be sold as a single milestone-gated engagement with a formal context-approval gate between them, normally 7–10 calendar weeks in total.",
    },

    # ---------------------------------------------------------------- OFFER B
    "b": {
        "title": "Offer B — Mining Demonstration Platform Definition | Spyke Technologies Inc.",
        "desc": "Requirements-level definition of a field-deployable mining demonstration platform: system requirements, modular configuration and interfaces, validation plan, traceability matrix and an executive build decision package.",
        "eyebrow": "Offer B",
        "h1": "Turn tested technology into a credible mining demonstrator.",
        "lead": "A requirements-level definition of the demonstration platform a mine customer can actually evaluate — what it must do, what mine workflow it must support, how it will be validated, and what evidence it must produce.",
        "cta_primary": "Define your demonstration platform",
        "purpose_label": "Purpose",
        "purpose_h2": "What this engagement answers.",
        "purpose_q": "What demonstrator should we build, what mine workflow must it support, and what evidence must it produce?",
        "purpose_p": "A laboratory system, a tripod-mounted sensor, an adapted industrial product or a pilot configuration is not a field-deployable demonstration platform. This engagement defines one, at requirements level, so detailed design and build can be authorized with confidence — or deliberately narrowed before unnecessary investment.",
        "entry_label": "Fit",
        "entry_h2": "Entry criteria.",
        "entry": [
            "Tested technology, a laboratory prototype or an early system.",
            "An approved Offer A demonstration context, or equivalent documented and client-approved application and context.",
            "A single technology platform and one primary demonstrator configuration, with at most two high-level secondary adaptation concepts.",
            "Intent to build, demonstrate or seek funding on the basis of the definition.",
        ],
        "work_label": "Method",
        "work_h2": "Workstreams.",
        "work": [
            ("Baseline confirmation and evidence review", "Establish a shared understanding of the approved demonstration context, the technology baseline, existing evidence, technical constraints and the intended demonstrator purpose."),
            ("Operational use-case definition", "Define the mine workflow the demonstrator must support, the operational decision it informs, the users involved, and the ground-truth basis for the evidence produced."),
            ("System requirements definition", "Specify functional, performance, environmental, mounting, power, compute, communications, spatial-reference, data-handling, HMI, setup, calibration, cleaning, maintenance, diagnostics and field-serviceability requirements."),
            ("Modular configuration and interface definition", "Separate the common core from application-specific adaptation, and define the mechanical, electrical, data and workflow interfaces between them."),
            ("Validation and demonstration planning", "Define demonstration objectives, success measures, ground-truth needs, verification methods, validation sequence, evidence thresholds and readiness gates."),
            ("Risk and decision framing", "Capture technical risks, assumptions, dependencies and decisions in a single register that survives the engagement."),
        ],
        "deliv_label": "Deliverables",
        "deliv_h2": "What you receive.",
        "deliv": [
            ("Operational Use-Case Definition", "The mine workflow, users, decision supported and ground-truth basis for the demonstration."),
            ("Mining Demonstration Platform System Requirements Specification", "The requirements-level definition of the field-deployable demonstrator."),
            ("Modular Configuration and Interface Definition", "Common core versus application-specific adaptation, with defined interfaces."),
            ("Validation and Customer Demonstration Plan", "Objectives, success measures, verification methods, sequence and evidence thresholds."),
            ("Requirements Traceability and Verification Matrix", "Each requirement linked to its verification method and evidence."),
            ("Technical Risk, Assumptions, Dependencies and Decision Register", "A living record of what is known, assumed, pending and decided."),
            ("Executive Decision Package", "A concise basis to authorize detailed design and build, narrow the demonstrator scope, or pause."),
        ],
        "out_label": "Boundaries",
        "out_h2": "Explicitly out of scope.",
        "out": [
            "Mining application framing, use-case selection or first demonstration-context approval — these are Offer A activities.",
            "More than one technology platform, or multiple independent mining applications, mine sites, geographies or customer-specific integration studies.",
            "Detailed mechanical, electrical, optical, firmware, software, data-science, manufacturing or production-product design.",
            "CAD models, fabrication drawings, PCB layouts, detailed bills of material, source code, algorithms, work instructions, test fixtures or engineering-release packages.",
            "Procurement, fabrication, assembly, integration, laboratory testing, installation, commissioning, hardware operation or field-trial execution.",
            "Formal certification, laboratory testing, regulatory filings, OEM approval, functional-safety analysis, safety-case preparation, detailed cybersecurity assessment or legal and compliance advice.",
            "Site visits, mine visits, travel, customer meetings, supplier meetings, external interviews or onsite workshops unless separately approved.",
            "Guaranteed sensing, classification, operational, technical, commercial, customer-acceptance, mine-site-access, certification, regulatory or schedule outcomes.",
            "Supplier qualification, partner contracting, commercial negotiation, sales representation or ongoing program management.",
        ],
        "deliv_model_label": "Delivery",
        "deliv_model_h2": "How it runs.",
        "deliv_model": [
            ("Duration", "Normally 5–7 calendar weeks after the demonstration context is approved. Combined with Offer A, normally 7–10 calendar weeks."),
            ("Mode", "Remote-first, with a structured kickoff, working sessions, draft review and an executive decision readout."),
            ("Commercial model", "Fixed scope, fixed fee, with stated assumptions, client inputs, acceptance criteria and exclusions. Where sold with Offer A, a formal context-approval gate separates the two."),
            ("Client inputs", "Approved application and demonstration context, technology baseline and evidence, technical point of contact, and timely review of draft deliverables."),
        ],
        "next_label": "Next decision",
        "next_h2": "What the definition enables.",
        "next_p": "A credible basis to authorize detailed design and build, conduct targeted validation, narrow the demonstrator scope, or pause before unnecessary investment. Once a representative demonstrator exists and has been exercised, Offer C establishes what must change before it can become a product.",
        "next_link_label": "Continue to Offer C",
        "next_link": "offer-c-mine-ready-productization-assessment.html",
        "combo": "Offers A and B may be sold together as one milestone-gated engagement, with a formal context-approval gate between them.",
    },

    # ---------------------------------------------------------------- OFFER C
    "c": {
        "title": "Offer C — Mine-Ready Productization Assessment | Spyke Technologies Inc.",
        "desc": "A structured assessment across seven domains that establishes the productization baseline, scorecard, gap register and an indicative 18–24 month roadmap from demonstrator to mine-ready product.",
        "eyebrow": "Offer C",
        "h1": "A demonstrator is not yet a mine-ready product.",
        "lead": "A structured, evidence-based assessment of what must change before a working demonstrator can be validated, manufactured, installed, serviced, supported and scaled — delivered as a baseline, a scorecard, a prioritized gap register and an indicative roadmap.",
        "cta_primary": "Assess your productization readiness",
        "purpose_label": "Purpose",
        "purpose_h2": "What this assessment answers.",
        "purpose_q": "What must change before the demonstrator can be deployed, validated, manufactured, serviced, supported and scaled?",
        "purpose_p": "Teams routinely underestimate this gap, not because the technology is weak, but because demonstrator success and product readiness are different problems. The assessment makes the remaining work visible, prioritized and defensible to an executive, an investor, a distributor or a major customer.",
        "entry_label": "Fit",
        "entry_h2": "Entry criteria.",
        "entry": [
            "A defined and approved mining application, and a representative working or field-validated demonstrator or prototype.",
            "A defined deployment context and workflow, with meaningful design, test, pilot or field evidence.",
            "One primary product, with no more than three meaningful variants or configurations.",
            "A single design-driving deployment context, selected collaboratively as the intended or worst-case operating context.",
            "Offer B is not a prerequisite where equivalent evidence already exists. Where application or demonstrator definition is materially unresolved, the honest recommendation is to route back to Offer A or B.",
        ],
        "dom_label": "Scope",
        "dom_h2": "Seven assessment domains.",
        "dom": [
            ("Product and system architecture", "Architecture, interfaces, assumptions, technical maturity and known failure modes; interactions across hardware, firmware, application and cloud software, communications, data flows and field processes; and which demonstrator elements can be retained, must be redesigned, or must be retired."),
            ("Mine environment and ruggedization", "Vibration, shock, thermal cycling, dust, moisture, ingress, corrosion, electrical noise, power quality, connectors, mounting, access and installation, assessed against the selected design-driving context."),
            ("Embedded, application, cloud, data and communications readiness", "Software and data architecture, connectivity, telemetry, configuration management, update paths and operational data handling at a productization-planning level."),
            ("Verification, validation, certification and compliance path", "The likely path, sequence and prerequisites — identified and planned, not executed or certified."),
            ("Manufacturability, testability and supply-chain readiness", "Design-for-manufacture and design-for-test observations, production test strategy, sourcing risk and supply-chain readiness."),
            ("Deployment, service and lifecycle support", "Installation, commissioning, diagnostics, spares, field service, escalation, upgrade and end-of-life considerations."),
            ("Channel and execution readiness", "Technical enablement, documentation, training and serviceability requirements implied by distributor or partner-led scale, and the organizational capability required to execute."),
        ],
        "deliv_label": "Deliverables",
        "deliv_h2": "What you receive.",
        "deliv": [
            ("Design-Driving Deployment Context Definition", "The selected intended or worst-case operating context that anchors the entire assessment."),
            ("Current-State Executive Summary", "A concise, evidence-based statement of where the product actually stands."),
            ("Demonstrator-to-Product Transition View", "What is retained, what is redesigned, and what provisional elements must be retired before commercial release."),
            ("Mine-Ready Productization Scorecard", "Readiness rated across the seven domains, with the evidence behind each rating."),
            ("Productization Gap Register", "Prioritized gaps with impact, dependency and recommended action."),
            ("Initial certification, validation and compliance path", "The likely sequence, prerequisites and planning implications."),
            ("Manufacturing and service findings", "Manufacturability, testability, supply-chain, deployment and support observations."),
            ("Recommended Delivery and Operating Model", "The resourcing, partner and governance model suited to the work ahead."),
            ("Indicative 18–24 month roadmap", "A sequenced, planning-level view of the path to mine-ready and channel-ready."),
            ("Recommended next-phase scope", "A concrete definition of the work that should follow, so the roadmap can be acted on."),
        ],
        "out_label": "Boundaries",
        "out_h2": "Explicitly out of scope.",
        "out": [
            "Re-definition of the first mining application, demonstration context or field demonstrator — these are Offer A and Offer B activities.",
            "Multiple independent products, product families or portfolio-level reviews; multiple mine sites, geographies or multi-customer studies.",
            "Final engineering design, detailed drawings, schematics, PCB layout, firmware or software development, source-code review, detailed bills of material, tooling, prototype build, production release or manufacturing launch.",
            "Functional-safety analysis, safety-integrity-level work, formal safety-case preparation or functional-safety certification.",
            "Detailed cybersecurity assessment, penetration testing, vulnerability assessment or security certification.",
            "Autonomous-control, machine-control, vehicle-control or control-system application analysis.",
            "Certification testing, formal compliance assessment, laboratory testing, regulatory filings, certification submission or certification approval.",
            "Site surveys, field testing, in-person meetings, mine visits, installation surveys or customer-specific detailed integration studies.",
            "Sourcing, formal qualification, audit, procurement, commercial negotiation, contracting or management of partners.",
            "Legal, regulatory, tax, financial, insurance, product-safety, product-liability, warranty or manufacturer-of-record opinions, and any warranty, field-performance, certification-outcome or schedule guarantee.",
        ],
        "deliv_model_label": "Delivery",
        "deliv_model_h2": "How it runs.",
        "deliv_model": [
            ("Duration", "Up to 4 calendar weeks from kickoff, subject to timely receipt of client inputs."),
            ("Mode", "Remote-first, with a structured kickoff, domain working sessions, draft review and an executive readout."),
            ("Commercial model", "Fixed scope, fixed fee, with stated assumptions, client inputs, acceptance criteria and exclusions."),
            ("Client inputs", "Architecture and design information, test and field evidence, demonstrator access or documentation, a technical point of contact, and timely review of draft deliverables. Missing evidence is documented as a risk, dependency or recommended next action rather than assumed."),
        ],
        "next_label": "Next decision",
        "next_h2": "What the assessment enables.",
        "next_p": "A defensible productization baseline that supports an investment decision, an investor or distributor conversation, a major customer commitment, or an internal go/no-go. Where the organization is ready to execute, the roadmap becomes the input to Offer D.",
        "next_link_label": "Continue to Offer D",
        "next_link": "offer-d-prototype-to-channel-readiness-program.html",
        "combo": "",
    },

    # ---------------------------------------------------------------- OFFER D
    "d": {
        "title": "Offer D — Prototype-to-Channel Readiness Program | Spyke Technologies Inc.",
        "desc": "A phased program — Surge, Execute, Maintenance — that converts an approved productization roadmap into governed execution, readiness-gate progress and client-owned delivery capability.",
        "eyebrow": "Offer D",
        "h1": "Turn your productization roadmap into a repeatable delivery capability.",
        "lead": "A phased program that converts an approved roadmap into an executable, governed plan, leads the approved work packages through readiness gates, and leaves your organization able to run the work itself.",
        "cta_primary": "Discuss your delivery path",
        "purpose_label": "Purpose",
        "purpose_h2": "What this program answers.",
        "purpose_q": "How do we convert the roadmap into an executable program and build the delivery capability required for scale?",
        "purpose_p": "A prioritized roadmap is not a plan. Execution fails when work packages have no owners, partner scopes have no interface control, acceptance criteria are undefined, and a small team is coordinating too many suppliers without clear technical authority. This program supplies that authority and transfers it.",
        "entry_label": "Fit",
        "entry_h2": "Entry criteria.",
        "entry": [
            "An approved productization baseline or roadmap, or equivalent documented evidence.",
            "An executive sponsor, a funding path and a named product owner.",
            "Decision authority and readiness to execute, not only to plan.",
            "Willingness to retain direct access to essential product, supplier, test, manufacturing, deployment, service and channel relationships.",
        ],
        "phase_label": "Structure",
        "phase_h2": "Three phases.",
        "phases": [
            ("Surge", "Normally 2–6 months", "Convert the roadmap into an executable, governed plan.", [
                "Execution Charter — objective, product and application boundary, design-driving deployment context, target outcome, constraints, success definition, assumptions and exclusions.",
                "Prioritized Execution Backlog and Work-Package Plan.",
                "Responsibility, Decision and Interface Matrix.",
                "Integrated Master Plan with a rolling 90-day plan.",
                "Resource and Partner Plan, with planning-level estimates or ranges by work package and third-party category — not a purchase authorization or third-party cost guarantee.",
                "Technical Governance and Control System, including readiness gates and acceptance criteria.",
                "Surge Exit Review and authorization decision.",
            ]),
            ("Execute", "Normally 6–18 months", "Lead the approved work packages through readiness gates.", [
                "Technical leadership of the authorized work packages, with defined interface control and acceptance criteria.",
                "Technical coordination of partners, specialists and suppliers contracted directly by the client.",
                "Readiness-gate reviews, risk reduction and decision support.",
                "Progressive capability transfer to the client's product owner and team.",
            ]),
            ("Maintenance", "Ongoing", "Retain senior technical continuity after active execution.", [
                "Periodic advisory continuity, technical review and decision support.",
                "Escalation path for defined technical questions arising after handover.",
                "Does not include emergency-response service levels, guaranteed response times, onsite support, travel, unlimited availability or active execution capacity.",
            ]),
        ],
        "work_label": "Role",
        "work_h2": "What Spyke Technologies does — and does not do.",
        "work": [
            ("Provides", "Senior technical leadership, program definition and governance, requirements and interface control, readiness-gate leadership, technical partner coordination, risk reduction, decision support and capability transfer."),
            ("Does not become", "Manufacturer of record, installer of record, certification body or laboratory, dealer, distributor, sales representative, or guarantor of the client's product or of third-party work — unless separately and explicitly agreed in writing with appropriate pricing, insurance, risk allocation and authority."),
            ("Client retains", "Product ownership, commercial authority, partner selection and expenditure approval, direct supplier and partner relationships, final product-release authority, and manufacturer-of-record responsibility including product safety, regulatory compliance, certification submissions and field performance."),
        ],
        "gov_label": "Governance",
        "gov_h2": "How progression is controlled.",
        "gov": [
            "The program normally begins with a scoped Surge phase under a separately approved proposal or statement of work.",
            "Progression from Surge to Execute requires separate authorization of the selected work packages, resource model, funding, technical governance and decision structure.",
            "Transition from Execute to Maintenance is available when active work packages are complete, handed off, paused or reduced to an advisory need.",
            "A material redesign, expanded deployment context, new product variant, major field issue, certification failure, supplier transition or channel-scale requirement normally requires a new phase or a targeted work package rather than informal expansion.",
        ],
        "deliv_model_label": "Delivery",
        "deliv_model_h2": "How it runs.",
        "deliv_model": [
            ("Duration", "Active program normally 8–24 months across Surge and Execute, with Maintenance available thereafter."),
            ("Mode", "Remote-first senior leadership, with the specialist delivery capacity the work requires contracted directly by the client wherever practical."),
            ("Commercial model", "Phase-based, separately scoped and authorized. Each phase states its objectives, deliverables, assumptions, client inputs, acceptance criteria and exclusions."),
            ("Client inputs", "Executive sponsorship, a named product owner, funding pathway, decision cadence, access to technical information, and direct contracting authority with delivery partners."),
        ],
        "next_label": "Outcome",
        "next_h2": "What the program leaves behind.",
        "next_p": "Readiness-gate progress against an approved plan, and an organization that can run the next product, the next variant and the next deployment without external dependency. A successful program ends with your team more capable, not more dependent.",
        "next_link_label": "Review the pathway",
        "next_link": "pathway.html",
        "combo": "",
    },
}
