# -*- coding: utf-8 -*-
"""Contenu détaillé français des offres A à D."""

OFFERS = {
    # ---------------------------------------------------------------- OFFRE A
    "a": {
        "title": "Offre A — Sprint de cadrage d’application minière | Spyke Technologies Inc.",
        "desc": "Un sprint ciblé qui sélectionne l’application minière prioritaire, définit le contexte de démonstration, cartographie les parties prenantes et produit une feuille de route de validation sur 90 jours.",
        "eyebrow": "Offre A",
        "h1": "Avant de construire pour la mine, définissez le bon problème minier.",
        "lead": "Un sprint court et structuré pour les équipes disposant d’une technologie crédible, mais sans application minière suffisamment définie. Il convertit une capacité technologique large en un cas d’usage minier prioritaire, un contexte de démonstration approuvé et un plan de preuve finançable.",
        "cta_primary": "Définir votre application minière",
        "purpose_label": "Objectif",
        "purpose_h2": "Ce à quoi répond ce sprint.",
        "purpose_q": "Où cette technologie peut-elle créer une valeur pratique en contexte minier, et que doit prouver un premier démonstrateur pertinent pour la mine?",
        "purpose_p": "La façon la plus rapide de construire le mauvais produit minier est de concevoir autour d’un cas d’usage présumé. Ce sprint établit le cas d’usage, le contexte d’exploitation, les parties prenantes qui peuvent approuver ou bloquer l’adoption, et les preuves qu’un premier démonstrateur doit produire — avant l’engagement de budgets d’ingénierie.",
        "entry_label": "Adéquation",
        "entry_h2": "Critères d’entrée.",
        "entry": [
            "Une technologie, capacité ou concept crédible — éprouvé en laboratoire, en projet pilote ou dans un secteur voisin.",
            "Aucune application minière, flux de travail cible, contexte de démonstration ou objectif de preuve suffisamment défini.",
            "Une seule plateforme technologique ou gamme de produits, et au plus trois applications minières candidates.",
            "Un commanditaire exécutif et une volonté d’agir sur la recommandation, y compris une recommandation de restreindre ou de suspendre.",
        ],
        "work_label": "Méthode",
        "work_h2": "Volets de travail.",
        "work": [
            ("Revue de la technologie et des preuves", "Établir une compréhension commune et fondée sur les preuves de la capacité actuelle, des différenciateurs crédibles, des limites et des contraintes, à partir des descriptions techniques, démonstrations, informations d’architecture et apprentissages de déploiement disponibles."),
            ("Cadrage des opportunités minières", "Identifier et comparer les applications minières candidates selon la valeur opérationnelle, la disponibilité des preuves, la faisabilité de démonstration, la friction d’adoption et le réalisme de déploiement."),
            ("Traduction du contexte d’exploitation", "Traduire l’application retenue en réalité minière : zone de travail, flux de travail de l’utilisateur, décision opérationnelle soutenue, exposition environnementale, contraintes d’installation et d’interface, alimentation, communications, données et autorisation de site."),
            ("Cartographie des parties prenantes et de l’adoption", "Identifier les utilisateurs opérationnels, évaluateurs techniques, responsables d’entretien et de sécurité, TI/TO, champions de site, commanditaires, responsables budgétaires et approvisionnement — et les preuves que chacun exige. Les entrevues externes directes ne sont pas incluses sauf si délimitées séparément."),
            ("Planification du démonstrateur et de la preuve", "Définir ce qu’un premier démonstrateur pertinent pour la mine doit prouver, ce qui en est volontairement exclu, et la séquence de validation des 90 jours suivants."),
        ],
        "deliv_label": "Livrables",
        "deliv_h2": "Ce que vous recevez.",
        "deliv": [
            ("Carte des opportunités minières", "Comparaison des applications candidates, avec un cas d’usage principal recommandé, un secondaire facultatif et les applications explicitement reportées ou exclues."),
            ("Brief de définition du contexte de démonstration", "Type de mine, zone de travail, flux de travail, conditions d’exploitation et contraintes qui orienteront le premier démonstrateur."),
            ("Carte des parties prenantes et de l’adoption", "Qui influence l’adoption, le rôle de chacun et les preuves que chacun exigera."),
            ("Brief environnement minier et considérations de démonstration", "Exposition environnementale, installation, alimentation, communications, données, sécurité et réalités d’autorisation de site qui façonnent une démonstration crédible."),
            ("Brief de décision sur le démonstrateur", "Ce qu’un premier démonstrateur doit prouver, ce qu’il ne doit pas tenter, et les critères de décision pour poursuivre."),
            ("Jeu de questions de découverte mené par le client", "Un ensemble structuré de questions que votre équipe utilise dans ses propres conversations avec les clients et les mines."),
            ("Feuille de route de validation sur 90 jours", "Un plan séquencé d’activités de validation, avec responsables et seuils de preuve."),
            ("Restitution exécutive", "Une séance de travail couvrant la recommandation, la justification et la prochaine décision."),
        ],
        "out_label": "Frontières",
        "out_h2": "Explicitement hors portée.",
        "out": [
            "Plus d’une plateforme technologique, ou une étude de marché large couvrant des segments miniers non liés.",
            "Dimensionnement de marché détaillé, prévisions, veille concurrentielle, stratégie de prix ou stratégie produit-marché finale.",
            "Entrevues directes avec des exploitants miniers, clients, OEM, concessionnaires, distributeurs, investisseurs, partenaires ou organismes de réglementation.",
            "Garantie d’introductions clients, d’accès à un site minier, de parrainage de projet pilote, de bons de commande, d’investissement, d’approbation de subvention, d’approbation réglementaire ou de certification.",
            "Visites de site ou de mine, déplacements, ateliers sur place, essais terrain, relevés d’installation ou mesures environnementales.",
            "Livrables de l’Offre B : spécification d’exigences système, définition modulaire et des interfaces, ou plan détaillé de validation et de démonstration client.",
            "Ingénierie détaillée : CAO, schémas, routage de circuits imprimés, micrologiciel, développement applicatif ou infonuagique, construction de prototype, nomenclatures détaillées ou exécution d’essais.",
            "Analyse ou opinion formelle en CEM, environnement, sécurité, sécurité fonctionnelle, cybersécurité, réglementation, certification, responsabilité produit, fiscalité, droit, assurance ou fabricant officiel.",
            "Approvisionnement, contractualisation de partenaires, qualification de fournisseurs, négociation commerciale, représentation commerciale ou gestion de travaux de tiers.",
        ],
        "deliv_model_label": "Déroulement",
        "deliv_model_h2": "Comment le mandat se déroule.",
        "deliv_model": [
            ("Durée", "1 à 2 semaines d’effort concentré, normalement complété en 2 à 3 semaines calendrier suivant le lancement et la réception des intrants du client."),
            ("Mode", "Principalement à distance, avec un lancement structuré, des séances de travail et une restitution exécutive."),
            ("Modèle commercial", "Portée fixe, honoraires fixes, avec hypothèses, intrants du client, critères d’acceptation et exclusions énoncés dans la proposition."),
            ("Intrants du client", "Description de la technologie et preuves disponibles, contacts clients ou miniers et apprentissages à ce jour, disponibilité du commanditaire, et revue rapide des livrables provisoires."),
        ],
        "next_label": "Prochaine décision",
        "next_h2": "Ce que le sprint rend possible.",
        "next_p": "Un démonstrateur financé et bien ciblé — ou une décision documentée de restreindre, pivoter, valider davantage ou arrêter. Une recommandation d’arrêter est un résultat légitime. Lorsque l’équipe poursuit, le contexte de démonstration approuvé devient la condition d’entrée de l’Offre B.",
        "next_link_label": "Poursuivre vers l’Offre B",
        "next_link": "offer-b-mining-demonstration-platform-definition.html",
        "combo": "Les Offres A et B peuvent être vendues comme un seul mandat à jalons, avec une porte formelle d’approbation du contexte entre les deux, normalement 7 à 10 semaines calendrier au total.",
    },

    # ---------------------------------------------------------------- OFFRE B
    "b": {
        "title": "Offre B — Définition de plateforme de démonstration minière | Spyke Technologies Inc.",
        "desc": "Définition au niveau des exigences d’une plateforme de démonstration minière déployable sur le terrain : exigences système, configuration modulaire et interfaces, plan de validation, matrice de traçabilité et dossier de décision exécutif.",
        "eyebrow": "Offre B",
        "h1": "Transformer une technologie éprouvée en démonstrateur minier crédible.",
        "lead": "Une définition, au niveau des exigences, de la plateforme de démonstration qu’un client minier peut réellement évaluer — ce qu’elle doit faire, quel flux de travail minier elle doit soutenir, comment elle sera validée et quelles preuves elle doit produire.",
        "cta_primary": "Définir votre plateforme de démonstration",
        "purpose_label": "Objectif",
        "purpose_h2": "Ce à quoi répond ce mandat.",
        "purpose_q": "Quel démonstrateur faut-il construire, quel flux de travail minier doit-il soutenir et quelles preuves doit-il produire?",
        "purpose_p": "Un système de laboratoire, un capteur sur trépied, un produit industriel adapté ou une configuration pilote n’est pas une plateforme de démonstration déployable sur le terrain. Ce mandat en définit une, au niveau des exigences, afin que la conception détaillée et la construction puissent être autorisées en confiance — ou délibérément restreintes avant un investissement inutile.",
        "entry_label": "Adéquation",
        "entry_h2": "Critères d’entrée.",
        "entry": [
            "Une technologie éprouvée, un prototype de laboratoire ou un système précoce.",
            "Un contexte de démonstration approuvé issu de l’Offre A, ou une documentation équivalente d’application et de contexte approuvée par le client.",
            "Une seule plateforme technologique et une configuration principale de démonstrateur, avec au plus deux concepts d’adaptation secondaires de haut niveau.",
            "L’intention de construire, de démontrer ou de rechercher du financement sur la base de cette définition.",
        ],
        "work_label": "Méthode",
        "work_h2": "Volets de travail.",
        "work": [
            ("Confirmation de la base et revue des preuves", "Établir une compréhension commune du contexte de démonstration approuvé, de la base technologique, des preuves existantes, des contraintes techniques et de la finalité visée du démonstrateur."),
            ("Définition du cas d’usage opérationnel", "Définir le flux de travail minier que le démonstrateur doit soutenir, la décision opérationnelle qu’il éclaire, les utilisateurs concernés et la base de vérité-terrain des preuves produites."),
            ("Définition des exigences système", "Spécifier les exigences fonctionnelles, de performance, environnementales, de montage, d’alimentation, de calcul, de communications, de référence spatiale, de traitement des données, d’IHM, d’installation, d’étalonnage, de nettoyage, d’entretien, de diagnostic et de maintenabilité terrain."),
            ("Configuration modulaire et interfaces", "Distinguer le tronc commun des adaptations spécifiques à l’application, et définir les interfaces mécaniques, électriques, de données et de flux de travail entre eux."),
            ("Planification de la validation et de la démonstration", "Définir les objectifs de démonstration, les mesures de succès, les besoins de vérité-terrain, les méthodes de vérification, la séquence de validation, les seuils de preuve et les jalons de préparation."),
            ("Cadrage des risques et des décisions", "Consigner les risques techniques, hypothèses, dépendances et décisions dans un registre unique qui survit au mandat."),
        ],
        "deliv_label": "Livrables",
        "deliv_h2": "Ce que vous recevez.",
        "deliv": [
            ("Définition du cas d’usage opérationnel", "Le flux de travail minier, les utilisateurs, la décision soutenue et la base de vérité-terrain de la démonstration."),
            ("Spécification d’exigences système de la plateforme de démonstration minière", "La définition, au niveau des exigences, du démonstrateur déployable sur le terrain."),
            ("Définition de la configuration modulaire et des interfaces", "Tronc commun et adaptations spécifiques à l’application, avec interfaces définies."),
            ("Plan de validation et de démonstration client", "Objectifs, mesures de succès, méthodes de vérification, séquence et seuils de preuve."),
            ("Matrice de traçabilité et de vérification des exigences", "Chaque exigence reliée à sa méthode de vérification et à ses preuves."),
            ("Registre des risques techniques, hypothèses, dépendances et décisions", "Un relevé vivant de ce qui est connu, présumé, en attente et décidé."),
            ("Dossier de décision exécutif", "Une base concise pour autoriser la conception détaillée et la construction, restreindre la portée du démonstrateur ou suspendre."),
        ],
        "out_label": "Frontières",
        "out_h2": "Explicitement hors portée.",
        "out": [
            "Cadrage de l’application minière, sélection du cas d’usage ou approbation du premier contexte de démonstration — ce sont des activités de l’Offre A.",
            "Plus d’une plateforme technologique, ou plusieurs applications minières indépendantes, sites miniers, territoires ou études d’intégration propres à un client.",
            "Conception mécanique, électrique, optique, micrologicielle, logicielle, de science des données, de fabrication ou de produit de série détaillée.",
            "Modèles CAO, dessins de fabrication, routages de circuits imprimés, nomenclatures détaillées, code source, algorithmes, instructions de travail, montages d’essai ou dossiers de mise en production.",
            "Approvisionnement, fabrication, assemblage, intégration, essais en laboratoire, installation, mise en service, exploitation du matériel ou exécution d’essais terrain.",
            "Certification formelle, essais en laboratoire, dépôts réglementaires, approbation OEM, analyse de sécurité fonctionnelle, préparation de dossier de sécurité, évaluation détaillée de cybersécurité ou conseil juridique et de conformité.",
            "Visites de site ou de mine, déplacements, rencontres clients ou fournisseurs, entrevues externes ou ateliers sur place, sauf approbation distincte.",
            "Garantie de résultats de détection, de classification, opérationnels, techniques, commerciaux, d’acceptation client, d’accès à un site minier, de certification, réglementaires ou d’échéancier.",
            "Qualification de fournisseurs, contractualisation de partenaires, négociation commerciale, représentation commerciale ou gestion de programme continue.",
        ],
        "deliv_model_label": "Déroulement",
        "deliv_model_h2": "Comment le mandat se déroule.",
        "deliv_model": [
            ("Durée", "Normalement 5 à 7 semaines calendrier après l’approbation du contexte de démonstration. Combiné à l’Offre A, normalement 7 à 10 semaines calendrier."),
            ("Mode", "Principalement à distance, avec un lancement structuré, des séances de travail, une revue des versions provisoires et une restitution décisionnelle."),
            ("Modèle commercial", "Portée fixe, honoraires fixes, avec hypothèses, intrants du client, critères d’acceptation et exclusions. Lorsqu’il est vendu avec l’Offre A, une porte formelle d’approbation du contexte sépare les deux."),
            ("Intrants du client", "Application et contexte de démonstration approuvés, base technologique et preuves, personne-ressource technique, et revue rapide des livrables provisoires."),
        ],
        "next_label": "Prochaine décision",
        "next_h2": "Ce que la définition rend possible.",
        "next_p": "Une base crédible pour autoriser la conception détaillée et la construction, mener une validation ciblée, restreindre la portée du démonstrateur ou suspendre avant un investissement inutile. Une fois qu’un démonstrateur représentatif existe et a été exercé, l’Offre C établit ce qui doit changer pour qu’il devienne un produit.",
        "next_link_label": "Poursuivre vers l’Offre C",
        "next_link": "offer-c-mine-ready-productization-assessment.html",
        "combo": "Les Offres A et B peuvent être vendues ensemble comme un seul mandat à jalons, avec une porte formelle d’approbation du contexte entre les deux.",
    },

    # ---------------------------------------------------------------- OFFRE C
    "c": {
        "title": "Offre C — Évaluation de productisation prête pour la mine | Spyke Technologies Inc.",
        "desc": "Une évaluation structurée sur sept domaines qui établit la base de productisation, la grille d’évaluation, le registre d’écarts et une feuille de route indicative de 18 à 24 mois du démonstrateur au produit prêt pour la mine.",
        "eyebrow": "Offre C",
        "h1": "Un démonstrateur n’est pas encore un produit prêt pour la mine.",
        "lead": "Une évaluation structurée et fondée sur les preuves de ce qui doit changer avant qu’un démonstrateur fonctionnel puisse être validé, fabriqué, installé, entretenu, soutenu et mis à l’échelle — livrée sous forme de base de référence, de grille d’évaluation, de registre d’écarts priorisé et de feuille de route indicative.",
        "cta_primary": "Évaluer votre préparation à la productisation",
        "purpose_label": "Objectif",
        "purpose_h2": "Ce à quoi répond cette évaluation.",
        "purpose_q": "Que faut-il changer avant que le démonstrateur puisse être déployé, validé, fabriqué, entretenu, soutenu et mis à l’échelle?",
        "purpose_p": "Les équipes sous-estiment régulièrement cet écart, non parce que la technologie est faible, mais parce que le succès d’un démonstrateur et la préparation d’un produit sont deux problèmes distincts. L’évaluation rend le travail restant visible, priorisé et défendable devant un dirigeant, un investisseur, un distributeur ou un client important.",
        "entry_label": "Adéquation",
        "entry_h2": "Critères d’entrée.",
        "entry": [
            "Une application minière définie et approuvée, et un démonstrateur ou prototype représentatif, fonctionnel ou validé sur le terrain.",
            "Un contexte de déploiement et un flux de travail définis, avec des preuves significatives de conception, d’essai, de projet pilote ou de terrain.",
            "Un produit principal, avec au plus trois variantes ou configurations significatives.",
            "Un seul contexte de déploiement structurant, choisi conjointement comme contexte d’exploitation visé ou le plus contraignant.",
            "L’Offre B n’est pas un prérequis lorsque des preuves équivalentes existent déjà. Lorsque la définition de l’application ou du démonstrateur demeure non résolue, la recommandation honnête est de réorienter vers l’Offre A ou B.",
        ],
        "dom_label": "Portée",
        "dom_h2": "Sept domaines d’évaluation.",
        "dom": [
            ("Architecture produit et système", "Architecture, interfaces, hypothèses, maturité technique et modes de défaillance connus; interactions entre le matériel, le micrologiciel, les logiciels applicatifs et infonuagiques, les communications, les flux de données et les processus terrain; et quels éléments du démonstrateur peuvent être conservés, doivent être reconçus ou doivent être retirés."),
            ("Environnement minier et robustification", "Vibration, choc, cycles thermiques, poussière, humidité, étanchéité, corrosion, bruit électrique, qualité de l’alimentation, connecteurs, montage, accès et installation, évalués selon le contexte structurant retenu."),
            ("Préparation embarquée, applicative, infonuagique, données et communications", "Architecture logicielle et de données, connectivité, télémétrie, gestion de configuration, parcours de mise à jour et traitement des données d’exploitation, au niveau de la planification de productisation."),
            ("Parcours de vérification, validation, certification et conformité", "Le parcours probable, sa séquence et ses prérequis — identifiés et planifiés, non exécutés ni certifiés."),
            ("Fabricabilité, testabilité et chaîne d’approvisionnement", "Observations de conception pour la fabrication et pour l’essai, stratégie d’essais de production, risques d’approvisionnement et préparation de la chaîne logistique."),
            ("Déploiement, service et soutien sur le cycle de vie", "Installation, mise en service, diagnostics, pièces de rechange, service terrain, escalade, mises à niveau et fin de vie."),
            ("Préparation du réseau et de l’exécution", "Habilitation technique, documentation, formation et exigences de maintenabilité qu’implique une mise à l’échelle par distributeurs ou partenaires, et la capacité organisationnelle requise pour exécuter."),
        ],
        "deliv_label": "Livrables",
        "deliv_h2": "Ce que vous recevez.",
        "deliv": [
            ("Définition du contexte de déploiement structurant", "Le contexte d’exploitation visé ou le plus contraignant qui ancre toute l’évaluation."),
            ("Sommaire exécutif de l’état actuel", "Un énoncé concis et fondé sur les preuves de la situation réelle du produit."),
            ("Vue de transition démonstrateur-produit", "Ce qui est conservé, ce qui est reconçu et quels éléments provisoires doivent être retirés avant la mise en marché."),
            ("Grille d’évaluation de productisation prête pour la mine", "La préparation cotée sur les sept domaines, avec les preuves sous-jacentes."),
            ("Registre d’écarts de productisation", "Écarts priorisés, avec impact, dépendance et action recommandée."),
            ("Parcours initial de certification, validation et conformité", "La séquence probable, les prérequis et les implications de planification."),
            ("Constats de fabrication et de service", "Observations de fabricabilité, testabilité, chaîne d’approvisionnement, déploiement et soutien."),
            ("Modèle de livraison et d’exploitation recommandé", "Le modèle de ressources, de partenaires et de gouvernance adapté au travail à venir."),
            ("Feuille de route indicative de 18 à 24 mois", "Une vue séquencée, au niveau de la planification, du chemin vers un produit prêt pour la mine et le réseau."),
            ("Portée recommandée de la phase suivante", "Une définition concrète du travail à venir, afin que la feuille de route puisse être mise en œuvre."),
        ],
        "out_label": "Frontières",
        "out_h2": "Explicitement hors portée.",
        "out": [
            "Redéfinition de la première application minière, du contexte de démonstration ou du premier démonstrateur terrain — ce sont des activités des Offres A et B.",
            "Plusieurs produits indépendants, gammes de produits ou revues de portefeuille; plusieurs sites miniers, territoires ou études multiclients.",
            "Conception d’ingénierie finale, dessins détaillés, schémas, routage de circuits imprimés, développement micrologiciel ou logiciel, revue de code source, nomenclature détaillée, outillage, construction de prototype, mise en production ou lancement de fabrication.",
            "Analyse de sécurité fonctionnelle, travaux de niveau d’intégrité de sécurité, préparation formelle de dossier de sécurité ou certification de sécurité fonctionnelle.",
            "Évaluation détaillée de cybersécurité, tests d’intrusion, évaluation de vulnérabilités ou certification de sécurité.",
            "Analyse d’applications de contrôle autonome, de contrôle machine, de contrôle de véhicule ou de systèmes de commande.",
            "Essais de certification, évaluation formelle de conformité, essais en laboratoire, dépôts réglementaires, soumission ou approbation de certification.",
            "Relevés de site, essais terrain, rencontres en personne, visites de mine, relevés d’installation ou études d’intégration détaillées propres à un client.",
            "Sourçage, qualification formelle, audit, approvisionnement, négociation commerciale, contractualisation ou gestion de partenaires.",
            "Opinions juridiques, réglementaires, fiscales, financières, d’assurance, de sécurité produit, de responsabilité produit, de garantie ou de fabricant officiel, ni aucune garantie de garantie, de performance terrain, de résultat de certification ou d’échéancier.",
        ],
        "deliv_model_label": "Déroulement",
        "deliv_model_h2": "Comment le mandat se déroule.",
        "deliv_model": [
            ("Durée", "Jusqu’à 4 semaines calendrier à compter du lancement, sous réserve de la réception rapide des intrants du client."),
            ("Mode", "Principalement à distance, avec un lancement structuré, des séances de travail par domaine, une revue des versions provisoires et une restitution exécutive."),
            ("Modèle commercial", "Portée fixe, honoraires fixes, avec hypothèses, intrants du client, critères d’acceptation et exclusions."),
            ("Intrants du client", "Informations d’architecture et de conception, preuves d’essai et de terrain, accès au démonstrateur ou à sa documentation, personne-ressource technique, et revue rapide des livrables provisoires. Les preuves manquantes sont consignées comme risque, dépendance ou action recommandée plutôt que présumées."),
        ],
        "next_label": "Prochaine décision",
        "next_h2": "Ce que l’évaluation rend possible.",
        "next_p": "Une base de productisation défendable qui soutient une décision d’investissement, une conversation avec un investisseur ou un distributeur, un engagement client important ou une revue interne de type « go/no-go ». Lorsque l’organisation est prête à exécuter, la feuille de route devient l’intrant de l’Offre D.",
        "next_link_label": "Poursuivre vers l’Offre D",
        "next_link": "offer-d-prototype-to-channel-readiness-program.html",
        "combo": "",
    },

    # ---------------------------------------------------------------- OFFRE D
    "d": {
        "title": "Offre D — Programme de préparation du prototype au réseau de distribution | Spyke Technologies Inc.",
        "desc": "Un programme par phases — Surge, Exécution, Maintien — qui convertit une feuille de route de productisation approuvée en exécution gouvernée, progression par jalons de préparation et capacité de livraison détenue par le client.",
        "eyebrow": "Offre D",
        "h1": "Transformer votre feuille de route de productisation en capacité de livraison reproductible.",
        "lead": "Un programme par phases qui convertit une feuille de route approuvée en plan exécutable et gouverné, dirige les lots de travail approuvés à travers les jalons de préparation, et laisse votre organisation capable de mener le travail elle-même.",
        "cta_primary": "Discuter de votre parcours de livraison",
        "purpose_label": "Objectif",
        "purpose_h2": "Ce à quoi répond ce programme.",
        "purpose_q": "Comment convertir la feuille de route en programme exécutable et bâtir la capacité de livraison requise pour la mise à l’échelle?",
        "purpose_p": "Une feuille de route priorisée n’est pas un plan. L’exécution échoue lorsque les lots de travail n’ont pas de responsables, que les portées des partenaires n’ont pas de contrôle d’interface, que les critères d’acceptation sont indéfinis et qu’une petite équipe coordonne trop de fournisseurs sans autorité technique claire. Ce programme fournit cette autorité, puis la transfère.",
        "entry_label": "Adéquation",
        "entry_h2": "Critères d’entrée.",
        "entry": [
            "Une base ou feuille de route de productisation approuvée, ou des preuves documentées équivalentes.",
            "Un commanditaire exécutif, une voie de financement et un responsable de produit désigné.",
            "L’autorité décisionnelle et la volonté d’exécuter, et non seulement de planifier.",
            "La volonté de conserver un accès direct aux relations essentielles de produit, fournisseurs, essais, fabrication, déploiement, service et distribution.",
        ],
        "phase_label": "Structure",
        "phase_h2": "Trois phases.",
        "phases": [
            ("Surge", "Normalement 2 à 6 mois", "Convertir la feuille de route en un plan exécutable et gouverné.", [
                "Charte d’exécution — objectif, frontière produit et application, contexte de déploiement structurant, résultat visé, contraintes, définition du succès, hypothèses et exclusions.",
                "Carnet d’exécution priorisé et plan des lots de travail.",
                "Matrice des responsabilités, des décisions et des interfaces.",
                "Plan directeur intégré avec plan glissant de 90 jours.",
                "Plan de ressources et de partenaires, avec estimations ou fourchettes au niveau de la planification par lot de travail et catégorie de tiers — ce n’est ni une autorisation d’achat ni une garantie de coût de tiers.",
                "Système de gouvernance et de contrôle technique, incluant jalons de préparation et critères d’acceptation.",
                "Revue de sortie de la phase Surge et décision d’autorisation.",
            ]),
            ("Exécution", "Normalement 6 à 18 mois", "Diriger les lots de travail approuvés à travers les jalons de préparation.", [
                "Leadership technique des lots de travail autorisés, avec contrôle des interfaces et critères d’acceptation définis.",
                "Coordination technique des partenaires, spécialistes et fournisseurs contractés directement par le client.",
                "Revues de jalons de préparation, réduction des risques et soutien à la décision.",
                "Transfert progressif de capacité vers le responsable de produit et l’équipe du client.",
            ]),
            ("Maintien", "En continu", "Conserver une continuité technique senior après l’exécution active.", [
                "Continuité consultative périodique, revue technique et soutien à la décision.",
                "Voie d’escalade pour les questions techniques définies survenant après le transfert.",
                "N’inclut pas d’engagements de niveau de service d’urgence, de délais de réponse garantis, de soutien sur place, de déplacements, de disponibilité illimitée ni de capacité d’exécution active.",
            ]),
        ],
        "work_label": "Rôle",
        "work_h2": "Ce que Spyke Technologies fait — et ne fait pas.",
        "work": [
            ("Fournit", "Leadership technique senior, définition et gouvernance du programme, contrôle des exigences et des interfaces, direction des jalons de préparation, coordination technique des partenaires, réduction des risques, soutien à la décision et transfert de capacité."),
            ("Ne devient pas", "Fabricant officiel, installateur officiel, organisme ou laboratoire de certification, concessionnaire, distributeur, représentant commercial, ni garant du produit du client ou des travaux de tiers — sauf entente écrite distincte et explicite assortie d’une tarification, d’assurances, d’une répartition des risques et d’une autorité appropriées."),
            ("Le client conserve", "La propriété du produit, l’autorité commerciale, la sélection des partenaires et l’approbation des dépenses, les relations directes avec les fournisseurs et partenaires, l’autorité finale de mise en production, et les responsabilités de fabricant officiel, y compris la sécurité du produit, la conformité réglementaire, les soumissions de certification et la performance terrain."),
        ],
        "gov_label": "Gouvernance",
        "gov_h2": "Comment la progression est encadrée.",
        "gov": [
            "Le programme débute normalement par une phase Surge délimitée, sous une proposition ou un énoncé de travaux approuvé séparément.",
            "Le passage de Surge à l’Exécution exige l’autorisation distincte des lots de travail retenus, du modèle de ressources, du financement, de la gouvernance technique et de la structure décisionnelle.",
            "La transition de l’Exécution au Maintien est possible lorsque les lots de travail actifs sont terminés, transférés, suspendus ou réduits à un besoin consultatif.",
            "Une refonte importante, un contexte de déploiement élargi, une nouvelle variante, un problème terrain majeur, un échec de certification, un changement de fournisseur ou une exigence d’échelle du réseau exige normalement une nouvelle phase ou un lot de travail ciblé plutôt qu’une expansion informelle.",
        ],
        "deliv_model_label": "Déroulement",
        "deliv_model_h2": "Comment le programme se déroule.",
        "deliv_model": [
            ("Durée", "Programme actif normalement de 8 à 24 mois entre Surge et Exécution, avec le Maintien disponible par la suite."),
            ("Mode", "Leadership senior principalement à distance, avec la capacité spécialisée requise contractée directement par le client lorsque possible."),
            ("Modèle commercial", "Par phases, délimitées et autorisées séparément. Chaque phase précise ses objectifs, livrables, hypothèses, intrants du client, critères d’acceptation et exclusions."),
            ("Intrants du client", "Parrainage exécutif, responsable de produit désigné, voie de financement, cadence décisionnelle, accès à l’information technique et autorité de contractualisation directe avec les partenaires de livraison."),
        ],
        "next_label": "Résultat",
        "next_h2": "Ce que le programme laisse derrière lui.",
        "next_p": "Une progression par jalons de préparation sur un plan approuvé, et une organisation capable de mener le prochain produit, la prochaine variante et le prochain déploiement sans dépendance externe. Un programme réussi se termine avec votre équipe plus capable, et non plus dépendante.",
        "next_link_label": "Revoir le parcours",
        "next_link": "pathway.html",
        "combo": "",
    },
}
